/*
01 Create Account
Create accounts for HR schema
Run this as either SYS or SYSTEM.
*/

SELECT * FROM DBA_PDBS; 
/*
Get the pdbs and replace with ORCLDB1
*/
ALTER SESSION SET CONTAINER = ORCLPDB1;

/*
If the above PDB name does not work, some options for PDB names are:
ALTER SESSION SET CONTAINER = ORCLPDB1;
ALTER SESSION SET CONTAINER = PDB1;
*/

/*
Drop the HR account and all objects to reset.
Then, create the user and give it the permissions.
*/
DROP USER HR CASCADE;

CREATE USER HR IDENTIFIED BY hr;

ALTER USER HR DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER HR TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO HR;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO HR;

ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT CONNECT, RESOURCE TO HR;
GRANT UNLIMITED TABLESPACE TO HR;

-- Optional: If you want to give HR full control over DB objects
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO HR;

/*
Open Sql Developer and in Service Name Use the CONTAINER name set in the below query
ALTER SESSION SET CONTAINER = ORCLPDB1;

*/
