INSERT ALL
INTO country (country_id, country_name) VALUES (1, 'Afghanistan')
INTO country (country_id, country_name) VALUES (2, 'Netherlands Antilles')
INTO country (country_id, country_name) VALUES (3, 'Albania')
INTO country (country_id, country_name) VALUES (4, 'Algeria')
INTO country (country_id, country_name) VALUES (5, 'Andorra')
INTO country (country_id, country_name) VALUES (6, 'Angola')
INTO country (country_id, country_name) VALUES (7, 'Antigua and Barbuda')
INTO country (country_id, country_name) VALUES (8, 'Australasia')
INTO country (country_id, country_name) VALUES (9, 'Argentina')
INTO country (country_id, country_name) VALUES (10, 'Armenia')
INTO country (country_id, country_name) VALUES (11, 'Aruba')
INTO country (country_id, country_name) VALUES (12, 'American Samoa')
INTO country (country_id, country_name) VALUES (13, 'Australia')
INTO country (country_id, country_name) VALUES (14, 'Austria')
INTO country (country_id, country_name) VALUES (15, 'Azerbaijan')
INTO country (country_id, country_name) VALUES (16, 'Bahamas')
INTO country (country_id, country_name) VALUES (17, 'Bangladesh')
INTO country (country_id, country_name) VALUES (18, 'Barbados')
INTO country (country_id, country_name) VALUES (19, 'Burundi')
INTO country (country_id, country_name) VALUES (20, 'Belgium')
INTO country (country_id, country_name) VALUES (21, 'Benin')
INTO country (country_id, country_name) VALUES (22, 'Bermuda')
INTO country (country_id, country_name) VALUES (23, 'Bhutan')
INTO country (country_id, country_name) VALUES (24, 'Bosnia and Herzegovina')
INTO country (country_id, country_name) VALUES (25, 'Belize')
INTO country (country_id, country_name) VALUES (26, 'Belarus')
INTO country (country_id, country_name) VALUES (27, 'Bohemia')
INTO country (country_id, country_name) VALUES (28, 'Boliva')
INTO country (country_id, country_name) VALUES (29, 'Botswana')
INTO country (country_id, country_name) VALUES (30, 'Brazil')
INTO country (country_id, country_name) VALUES (31, 'Bahrain')
INTO country (country_id, country_name) VALUES (32, 'Brunei')
INTO country (country_id, country_name) VALUES (33, 'Bulgaria')
INTO country (country_id, country_name) VALUES (34, 'Burkina Faso')
INTO country (country_id, country_name) VALUES (35, 'Central African Republic')
INTO country (country_id, country_name) VALUES (36, 'Cambodia')
INTO country (country_id, country_name) VALUES (37, 'Canada')
INTO country (country_id, country_name) VALUES (38, 'Cayman Islands')
INTO country (country_id, country_name) VALUES (39, 'Republic of Congo')
INTO country (country_id, country_name) VALUES (40, 'Chad')
INTO country (country_id, country_name) VALUES (41, 'Chile')
INTO country (country_id, country_name) VALUES (42, 'China')
INTO country (country_id, country_name) VALUES (43, 'Ivory Coast')
INTO country (country_id, country_name) VALUES (44, 'Cameroon')
INTO country (country_id, country_name) VALUES (45, 'Democratic Republic of the Congo')
INTO country (country_id, country_name) VALUES (46, 'Cook Islands')
INTO country (country_id, country_name) VALUES (47, 'Colombia')
INTO country (country_id, country_name) VALUES (48, 'Comoros')
INTO country (country_id, country_name) VALUES (49, 'Cape Verde')
INTO country (country_id, country_name) VALUES (50, 'Costa Rica')
INTO country (country_id, country_name) VALUES (51, 'Croatia')
INTO country (country_id, country_name) VALUES (52, 'Crete')
INTO country (country_id, country_name) VALUES (53, 'Cuba')
INTO country (country_id, country_name) VALUES (54, 'Cyprus')
INTO country (country_id, country_name) VALUES (55, 'Czech Republic')
INTO country (country_id, country_name) VALUES (56, 'Denmark')
INTO country (country_id, country_name) VALUES (57, 'Djibouti')
INTO country (country_id, country_name) VALUES (58, 'Dominica')
INTO country (country_id, country_name) VALUES (59, 'Dominican Republic')
INTO country (country_id, country_name) VALUES (60, 'Ecuador')
INTO country (country_id, country_name) VALUES (61, 'Egypt')
INTO country (country_id, country_name) VALUES (62, 'Eritrea')
INTO country (country_id, country_name) VALUES (63, 'El Salvador')
INTO country (country_id, country_name) VALUES (64, 'Spain')
INTO country (country_id, country_name) VALUES (65, 'Estonia')
INTO country (country_id, country_name) VALUES (66, 'Ethiopia')
INTO country (country_id, country_name) VALUES (67, 'Unified Team')
INTO country (country_id, country_name) VALUES (68, 'Fiji')
INTO country (country_id, country_name) VALUES (69, 'Finland')
INTO country (country_id, country_name) VALUES (70, 'France')
INTO country (country_id, country_name) VALUES (71, 'West Germany')
INTO country (country_id, country_name) VALUES (72, 'Micronesia')
INTO country (country_id, country_name) VALUES (73, 'Gabon')
INTO country (country_id, country_name) VALUES (74, 'Gambia')
INTO country (country_id, country_name) VALUES (75, 'United Kingdom')
INTO country (country_id, country_name) VALUES (76, 'Guinea-Bissau')
INTO country (country_id, country_name) VALUES (77, 'East Germany')
INTO country (country_id, country_name) VALUES (78, 'Georgia')
INTO country (country_id, country_name) VALUES (79, 'Equatorial Guinea')
INTO country (country_id, country_name) VALUES (80, 'Germany')
INTO country (country_id, country_name) VALUES (81, 'Ghana')
INTO country (country_id, country_name) VALUES (82, 'Greece')
INTO country (country_id, country_name) VALUES (83, 'Grenada')
INTO country (country_id, country_name) VALUES (84, 'Guatemala')
INTO country (country_id, country_name) VALUES (85, 'Guinea')
INTO country (country_id, country_name) VALUES (86, 'Guam')
INTO country (country_id, country_name) VALUES (87, 'Guyana')
INTO country (country_id, country_name) VALUES (88, 'Haiti')
INTO country (country_id, country_name) VALUES (89, 'Hong Kong')
INTO country (country_id, country_name) VALUES (90, 'Honduras')
INTO country (country_id, country_name) VALUES (91, 'Hungary')
INTO country (country_id, country_name) VALUES (92, 'Indonesia')
INTO country (country_id, country_name) VALUES (93, 'India')
INTO country (country_id, country_name) VALUES (94, 'Individual Olympic Athletes')
INTO country (country_id, country_name) VALUES (95, 'Iran')
INTO country (country_id, country_name) VALUES (96, 'Ireland')
INTO country (country_id, country_name) VALUES (97, 'Iraq')
INTO country (country_id, country_name) VALUES (98, 'Iceland')
INTO country (country_id, country_name) VALUES (99, 'Israel')
INTO country (country_id, country_name) VALUES (100, 'Virgin Islands')
INTO country (country_id, country_name) VALUES (101, 'Italy')
INTO country (country_id, country_name) VALUES (102, 'Virgin Islands, British')
INTO country (country_id, country_name) VALUES (103, 'Jamaica')
INTO country (country_id, country_name) VALUES (104, 'Jordan')
INTO country (country_id, country_name) VALUES (105, 'Japan')
INTO country (country_id, country_name) VALUES (106, 'Kazakhstan')
INTO country (country_id, country_name) VALUES (107, 'Kenya')
INTO country (country_id, country_name) VALUES (108, 'Kyrgyzstan')
INTO country (country_id, country_name) VALUES (109, 'Kiribati')
INTO country (country_id, country_name) VALUES (110, 'South Korea')
INTO country (country_id, country_name) VALUES (111, 'Kosovo')
INTO country (country_id, country_name) VALUES (112, 'Saudi Arabia')
INTO country (country_id, country_name) VALUES (113, 'Kuwait')
INTO country (country_id, country_name) VALUES (114, 'Laos')
INTO country (country_id, country_name) VALUES (115, 'Latvia')
INTO country (country_id, country_name) VALUES (116, 'Libya')
INTO country (country_id, country_name) VALUES (117, 'Liberia')
INTO country (country_id, country_name) VALUES (118, 'Saint Lucia')
INTO country (country_id, country_name) VALUES (119, 'Lesotho')
INTO country (country_id, country_name) VALUES (120, 'Lebanon')
INTO country (country_id, country_name) VALUES (121, 'Liechtenstein')
INTO country (country_id, country_name) VALUES (122, 'Lithuania')
INTO country (country_id, country_name) VALUES (123, 'Luxembourg')
INTO country (country_id, country_name) VALUES (124, 'Madagascar')
INTO country (country_id, country_name) VALUES (125, 'Malaya')
INTO country (country_id, country_name) VALUES (126, 'Morocco')
INTO country (country_id, country_name) VALUES (127, 'Malaysia')
INTO country (country_id, country_name) VALUES (128, 'Malawi')
INTO country (country_id, country_name) VALUES (129, 'Moldova')
INTO country (country_id, country_name) VALUES (130, 'Maldives')
INTO country (country_id, country_name) VALUES (131, 'Mexico')
INTO country (country_id, country_name) VALUES (132, 'Mongolia')
INTO country (country_id, country_name) VALUES (133, 'Marshall Islands')
INTO country (country_id, country_name) VALUES (134, 'Macedonia')
INTO country (country_id, country_name) VALUES (135, 'Mali')
INTO country (country_id, country_name) VALUES (136, 'Malta')
INTO country (country_id, country_name) VALUES (137, 'Montenegro')
INTO country (country_id, country_name) VALUES (138, 'Monaco')
INTO country (country_id, country_name) VALUES (139, 'Mozambique')
INTO country (country_id, country_name) VALUES (140, 'Mauritius')
INTO country (country_id, country_name) VALUES (141, 'Mauritania')
INTO country (country_id, country_name) VALUES (142, 'Myanmar')
INTO country (country_id, country_name) VALUES (143, 'Namibia')
INTO country (country_id, country_name) VALUES (144, 'North Borneo')
INTO country (country_id, country_name) VALUES (145, 'Nicaragua')
INTO country (country_id, country_name) VALUES (146, 'Netherlands')
INTO country (country_id, country_name) VALUES (147, 'Nepal')
INTO country (country_id, country_name) VALUES (148, 'Newfoundland')
INTO country (country_id, country_name) VALUES (149, 'Nigeria')
INTO country (country_id, country_name) VALUES (150, 'Niger')
INTO country (country_id, country_name) VALUES (151, 'Norway')
INTO country (country_id, country_name) VALUES (152, 'Nauru')
INTO country (country_id, country_name) VALUES (153, 'New Zealand')
INTO country (country_id, country_name) VALUES (154, 'Oman')
INTO country (country_id, country_name) VALUES (155, 'Pakistan')
INTO country (country_id, country_name) VALUES (156, 'Panama')
INTO country (country_id, country_name) VALUES (157, 'Paraguay')
INTO country (country_id, country_name) VALUES (158, 'Peru')
INTO country (country_id, country_name) VALUES (159, 'Philippines')
INTO country (country_id, country_name) VALUES (160, 'Palestine')
INTO country (country_id, country_name) VALUES (161, 'Palau')
INTO country (country_id, country_name) VALUES (162, 'Papua New Guinea')
INTO country (country_id, country_name) VALUES (163, 'Poland')
INTO country (country_id, country_name) VALUES (164, 'Portugal')
INTO country (country_id, country_name) VALUES (165, 'North Korea')
INTO country (country_id, country_name) VALUES (166, 'Puerto Rico')
INTO country (country_id, country_name) VALUES (167, 'Qatar')
INTO country (country_id, country_name) VALUES (168, 'Zimbabwe INTO country (country_id, country_name) VALUES (Rhodesia)')
INTO country (country_id, country_name) VALUES (169, 'Refugee Olympic Team')
INTO country (country_id, country_name) VALUES (170, 'Romania')
INTO country (country_id, country_name) VALUES (171, 'South Africa')
INTO country (country_id, country_name) VALUES (172, 'Russia')
INTO country (country_id, country_name) VALUES (173, 'Rwanda')
INTO country (country_id, country_name) VALUES (174, 'Saar')
INTO country (country_id, country_name) VALUES (175, 'Samoa')
INTO country (country_id, country_name) VALUES (176, 'Serbia and Montenegro')
INTO country (country_id, country_name) VALUES (177, 'Senegal')
INTO country (country_id, country_name) VALUES (178, 'Seychelles')
INTO country (country_id, country_name) VALUES (179, 'Singapore')
INTO country (country_id, country_name) VALUES (180, 'Turks and Caicos Islands')
INTO country (country_id, country_name) VALUES (181, 'Sierra Leone')
INTO country (country_id, country_name) VALUES (182, 'Slovenia')
INTO country (country_id, country_name) VALUES (183, 'San Marino')
INTO country (country_id, country_name) VALUES (184, 'Solomon Islands')
INTO country (country_id, country_name) VALUES (185, 'Somalia')
INTO country (country_id, country_name) VALUES (186, 'Serbia')
INTO country (country_id, country_name) VALUES (187, 'Sri Lanka')
INTO country (country_id, country_name) VALUES (188, 'South Sudan')
INTO country (country_id, country_name) VALUES (189, 'Sao Tome and Principe')
INTO country (country_id, country_name) VALUES (190, 'Sudan')
INTO country (country_id, country_name) VALUES (191, 'Switzerland')
INTO country (country_id, country_name) VALUES (192, 'Suriname')
INTO country (country_id, country_name) VALUES (193, 'Slovakia')
INTO country (country_id, country_name) VALUES (194, 'Sweden')
INTO country (country_id, country_name) VALUES (195, 'Swaziland')
INTO country (country_id, country_name) VALUES (196, 'Syria')
INTO country (country_id, country_name) VALUES (197, 'Tanzania')
INTO country (country_id, country_name) VALUES (198, 'Czechoslovakia')
INTO country (country_id, country_name) VALUES (199, 'Tonga')
INTO country (country_id, country_name) VALUES (200, 'Thailand')
INTO country (country_id, country_name) VALUES (201, 'Tajikistan')
INTO country (country_id, country_name) VALUES (202, 'Turkmenistan')
INTO country (country_id, country_name) VALUES (203, 'Timor-Leste')
INTO country (country_id, country_name) VALUES (204, 'Togo')
INTO country (country_id, country_name) VALUES (205, 'Taiwan')
INTO country (country_id, country_name) VALUES (206, 'Trinidad and Tobago')
INTO country (country_id, country_name) VALUES (207, 'Tunisia')
INTO country (country_id, country_name) VALUES (208, 'Turkey')
INTO country (country_id, country_name) VALUES (209, 'Tuvalu')
INTO country (country_id, country_name) VALUES (210, 'United Arab Emirates')
INTO country (country_id, country_name) VALUES (211, 'United Arab Republic')
INTO country (country_id, country_name) VALUES (212, 'Uganda')
INTO country (country_id, country_name) VALUES (213, 'Ukraine')
INTO country (country_id, country_name) VALUES (214, 'Unknown')
INTO country (country_id, country_name) VALUES (215, 'Soviet Union')
INTO country (country_id, country_name) VALUES (216, 'Uruguay')
INTO country (country_id, country_name) VALUES (217, 'United States of America')
INTO country (country_id, country_name) VALUES (218, 'Uzbekistan')
INTO country (country_id, country_name) VALUES (219, 'Vanuatu')
INTO country (country_id, country_name) VALUES (220, 'Venezuela')
INTO country (country_id, country_name) VALUES (221, 'Vietnam')
INTO country (country_id, country_name) VALUES (222, 'Saint Vincent')
INTO country (country_id, country_name) VALUES (223, 'Vietnam INTO country (country_id, country_name) VALUES (pre)')
INTO country (country_id, country_name) VALUES (224, 'West Indies Federation')
INTO country (country_id, country_name) VALUES (225, 'North Yemen')
INTO country (country_id, country_name) VALUES (226, 'Yemen')
INTO country (country_id, country_name) VALUES (227, 'South Yemen')
INTO country (country_id, country_name) VALUES (228, 'Yugoslavia')
INTO country (country_id, country_name) VALUES (229, 'Zambia')
INTO country (country_id, country_name) VALUES (230, 'Zimbabwe')
INTO country (country_id, country_name) VALUES (231, 'Singapore')
INTO country (country_id, country_name) VALUES (232, 'French Polynesia') SELECT * FROM dual;

COMMIT;
