-- Warning: Don't delete the recently created tables
-- query to drop the tables:
--DROP TABLE alignment;
--DROP TABLE attrs;
--DROP TABLE colour;
--DROP TABLE gender;
--DROP TABLE race;
--DROP TABLE publisher;
--DROP TABLE superpower;

CREATE TABLE alignment (
  id NUMBER(11) NOT NULL,
  alignment varchar2(10) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO alignment (id, alignment) VALUES (1,'Good')
INTO alignment (id, alignment) VALUES (2,'Bad')
INTO alignment (id, alignment) VALUES (3,'Neutral')
INTO alignment (id, alignment) VALUES (4,'N/A')
SELECT * FROM dual;

-- renamed table, because attribute is a reserved word, will not work in 02_hero_attrs
CREATE TABLE attrs (
  id NUMBER(11) NOT NULL,
  attribute_name varchar2(200) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO attrs (id, attribute_name) VALUES (1,'Intelligence')
INTO attrs (id, attribute_name) VALUES (2,'Strength')
INTO attrs (id, attribute_name) VALUES (3,'Speed')
INTO attrs (id, attribute_name) VALUES (4,'Durability')
INTO attrs (id, attribute_name) VALUES (5,'Power')
INTO attrs (id, attribute_name) VALUES (6,'Combat')
SELECT * FROM dual;
-- without select throws an error

CREATE TABLE colour (
  id NUMBER(11) NOT NULL,
  colour varchar2(20) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
-- added column names here, were missing
INTO colour (id, colour) VALUES (1,'No Colour')
INTO colour (id, colour) VALUES (2,'Amber')
INTO colour (id, colour) VALUES (3,'Auburn')
INTO colour (id, colour) VALUES (4,'Black')
INTO colour (id, colour) VALUES (5,'Black/Blue')
INTO colour (id, colour) VALUES (6,'Blond')
INTO colour (id, colour) VALUES (7,'Blue')
INTO colour (id, colour) VALUES (8,'Blue/White')
INTO colour (id, colour) VALUES (9,'Brown')
INTO colour (id, colour) VALUES (10,'Brown/Black')
INTO colour (id, colour) VALUES (11,'Brown/White')
INTO colour (id, colour) VALUES (12,'Gold')
INTO colour (id, colour) VALUES (13,'Grey')
INTO colour (id, colour) VALUES (14,'Green')
INTO colour (id, colour) VALUES (15,'Green/Blue')
INTO colour (id, colour) VALUES (16,'Hazel')
INTO colour (id, colour) VALUES (17,'Indigo')
INTO colour (id, colour) VALUES (18,'Magenta')
INTO colour (id, colour) VALUES (19,'Orange')
INTO colour (id, colour) VALUES (20,'Orange/White')
INTO colour (id, colour) VALUES (21,'Pink')
INTO colour (id, colour) VALUES (22,'Purple')
INTO colour (id, colour) VALUES (23,'Red')
INTO colour (id, colour) VALUES (24,'Red/Black')
INTO colour (id, colour) VALUES (25,'Red/Grey')
INTO colour (id, colour) VALUES (26,'Red/Orange')
INTO colour (id, colour) VALUES (27,'Red/White')
INTO colour (id, colour) VALUES (28,'Silver')
INTO colour (id, colour) VALUES (29,'Strawberry Blond')
INTO colour (id, colour) VALUES (30,'Violet')
INTO colour (id, colour) VALUES (31,'White')
INTO colour (id, colour) VALUES (32,'White/Red')
INTO colour (id, colour) VALUES (33,'Yellow')
INTO colour (id, colour) VALUES (34,'Yellow/Blue')
INTO colour (id, colour) VALUES (35,'Yellow/Red')
SELECT * FROM dual;

CREATE TABLE gender (
  id NUMBER(11) NOT NULL,
  gender varchar2(20) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO gender (id, gender) VALUES (1,'Male')
INTO gender (id, gender) VALUES (2,'Female')
INTO gender (id, gender) VALUES (3,'N/A')
SELECT * FROM dual;

--moved race here from the sample data
CREATE TABLE race (
  id NUMBER(11) NOT NULL,
  race varchar2(100) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO race (id, race) VALUES (1,'-')
INTO race (id, race) VALUES (2,'Alien')
INTO race (id, race) VALUES (3,'Alpha')
INTO race (id, race) VALUES (4,'Amazon')
INTO race (id, race) VALUES (5,'Android')
INTO race (id, race) VALUES (6,'Animal')
INTO race (id, race) VALUES (7,'Asgardian')
INTO race (id, race) VALUES (8,'Atlantean')
INTO race (id, race) VALUES (9,'Bizarro')
INTO race (id, race) VALUES (10,'Bolovaxian')
INTO race (id, race) VALUES (11,'Clone')
INTO race (id, race) VALUES (12,'Cosmic Entity')
INTO race (id, race) VALUES (13,'Cyborg')
INTO race (id, race) VALUES (14,'Czarnian')
INTO race (id, race) VALUES (15,'Dathomirian Zabrak')
INTO race (id, race) VALUES (16,'Demi-God')
INTO race (id, race) VALUES (17,'Demon')
INTO race (id, race) VALUES (18,'Eternal')
INTO race (id, race) VALUES (19,'Flora Colossus')
INTO race (id, race) VALUES (20,'Frost Giant')
INTO race (id, race) VALUES (21,'God / Eternal')
INTO race (id, race) VALUES (22,'Gorilla')
INTO race (id, race) VALUES (23,'Gungan')
INTO race (id, race) VALUES (24,'Human')
INTO race (id, race) VALUES (25,'Human / Altered')
INTO race (id, race) VALUES (26,'Human / Clone')
INTO race (id, race) VALUES (27,'Human / Cosmic')
INTO race (id, race) VALUES (28,'Human / Radiation')
INTO race (id, race) VALUES (29,'Human-Kree')
INTO race (id, race) VALUES (30,'Human-Spartoi')
INTO race (id, race) VALUES (31,'Human-Vulcan')
INTO race (id, race) VALUES (32,'Human-Vuldarian')
INTO race (id, race) VALUES (33,'Icthyo Sapien')
INTO race (id, race) VALUES (34,'Inhuman')
INTO race (id, race) VALUES (35,'Kakarantharaian')
INTO race (id, race) VALUES (36,'Korugaran')
INTO race (id, race) VALUES (37,'Kryptonian')
INTO race (id, race) VALUES (38,'Luphomoid')
INTO race (id, race) VALUES (39,'Maiar')
INTO race (id, race) VALUES (40,'Martian')
INTO race (id, race) VALUES (41,'Metahuman')
INTO race (id, race) VALUES (42,'Mutant')
INTO race (id, race) VALUES (43,'Mutant / Clone')
INTO race (id, race) VALUES (44,'New God')
INTO race (id, race) VALUES (45,'Neyaphem')
INTO race (id, race) VALUES (46,'Parademon')
INTO race (id, race) VALUES (47,'Planet')
INTO race (id, race) VALUES (48,'Rodian')
INTO race (id, race) VALUES (49,'Saiyan')
INTO race (id, race) VALUES (50,'Spartoi')
INTO race (id, race) VALUES (51,'Strontian')
INTO race (id, race) VALUES (52,'Symbiote')
INTO race (id, race) VALUES (53,'Talokite')
INTO race (id, race) VALUES (54,'Tamaranean')
INTO race (id, race) VALUES (55,'Ungaran')
INTO race (id, race) VALUES (56,'Vampire')
INTO race (id, race) VALUES (57,'Xenomorph XX121')
INTO race (id, race) VALUES (58,'Yautja')
-- to escape the character in Oracle DB not a backslash, but a double quote is used :)
INTO race (id, race) VALUES (59,'Yoda''s species')
INTO race (id, race) VALUES (60,'Zen-Whoberian')
INTO race (id, race) VALUES (61,'Zombie')
SELECT * FROM dual;

--moved publisher here
CREATE TABLE publisher (
  id NUMBER(11) NOT NULL,
  publisher_name varchar2(50) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO publisher (id, publisher_name) VALUES (1,'')
INTO publisher (id, publisher_name) VALUES (2,'ABC Studios')
INTO publisher (id, publisher_name) VALUES (3,'Dark Horse Comics')
INTO publisher (id, publisher_name) VALUES (4,'DC Comics')
INTO publisher (id, publisher_name) VALUES (5,'George Lucas')
INTO publisher (id, publisher_name) VALUES (6,'Hanna-Barbera')
INTO publisher (id, publisher_name) VALUES (7,'HarperCollins')
INTO publisher (id, publisher_name) VALUES (8,'Icon Comics')
INTO publisher (id, publisher_name) VALUES (9,'IDW Publishing')
INTO publisher (id, publisher_name) VALUES (10,'Image Comics')
INTO publisher (id, publisher_name) VALUES (11,'J. K. Rowling')
INTO publisher (id, publisher_name) VALUES (12,'J. R. R. Tolkien')
INTO publisher (id, publisher_name) VALUES (13,'Marvel Comics')
INTO publisher (id, publisher_name) VALUES (14,'Microsoft')
INTO publisher (id, publisher_name) VALUES (15,'NBC - Heroes')
INTO publisher (id, publisher_name) VALUES (16,'Rebellion')
INTO publisher (id, publisher_name) VALUES (17,'Shueisha')
INTO publisher (id, publisher_name) VALUES (18,'Sony Pictures')
INTO publisher (id, publisher_name) VALUES (19,'South Park')
INTO publisher (id, publisher_name) VALUES (20,'Star Trek')
INTO publisher (id, publisher_name) VALUES (21,'SyFy')
INTO publisher (id, publisher_name) VALUES (22,'Team Epic TV')
INTO publisher (id, publisher_name) VALUES (23,'Titan Books')
INTO publisher (id, publisher_name) VALUES (24,'Universal Studios')
INTO publisher (id, publisher_name) VALUES (25,'Wildstorm')
SELECT * FROM dual;

--superpower
CREATE TABLE superpower (
  id number(11) NOT NULL,
  power_name varchar2(200) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT ALL
INTO superpower (id, power_name) VALUES (1,'Agility')
INTO superpower (id, power_name) VALUES (2,'Accelerated Healing')
INTO superpower (id, power_name) VALUES (3,'Lantern Power Ring')
INTO superpower (id, power_name) VALUES (4,'Dimensional Awareness')
INTO superpower (id, power_name) VALUES (5,'Cold Resistance')
INTO superpower (id, power_name) VALUES (6,'Durability')
INTO superpower (id, power_name) VALUES (7,'Stealth')
INTO superpower (id, power_name) VALUES (8,'Energy Absorption')
INTO superpower (id, power_name) VALUES (9,'Flight')
INTO superpower (id, power_name) VALUES (10,'Danger Sense')
INTO superpower (id, power_name) VALUES (11,'Underwater breathing')
INTO superpower (id, power_name) VALUES (12,'Marksmanship')
INTO superpower (id, power_name) VALUES (13,'Weapons Master')
INTO superpower (id, power_name) VALUES (14,'Power Augmentation')
INTO superpower (id, power_name) VALUES (15,'Animal Attributes')
INTO superpower (id, power_name) VALUES (16,'Longevity')
INTO superpower (id, power_name) VALUES (17,'Intelligence')
INTO superpower (id, power_name) VALUES (18,'Super Strength')
INTO superpower (id, power_name) VALUES (19,'Cryokinesis')
INTO superpower (id, power_name) VALUES (20,'Telepathy')
INTO superpower (id, power_name) VALUES (21,'Energy Armor')
INTO superpower (id, power_name) VALUES (22,'Energy Blasts')
INTO superpower (id, power_name) VALUES (23,'Duplication')
INTO superpower (id, power_name) VALUES (24,'Size Changing')
INTO superpower (id, power_name) VALUES (25,'Density Control')
INTO superpower (id, power_name) VALUES (26,'Stamina')
INTO superpower (id, power_name) VALUES (27,'Astral Travel')
INTO superpower (id, power_name) VALUES (28,'Audio Control')
INTO superpower (id, power_name) VALUES (29,'Dexterity')
INTO superpower (id, power_name) VALUES (30,'Omnitrix')
INTO superpower (id, power_name) VALUES (31,'Super Speed')
INTO superpower (id, power_name) VALUES (32,'Possession')
INTO superpower (id, power_name) VALUES (33,'Animal Oriented Powers')
INTO superpower (id, power_name) VALUES (34,'Weapon-based Powers')
INTO superpower (id, power_name) VALUES (35,'Electrokinesis')
INTO superpower (id, power_name) VALUES (36,'Darkforce Manipulation')
INTO superpower (id, power_name) VALUES (37,'Death Touch')
INTO superpower (id, power_name) VALUES (38,'Teleportation')
INTO superpower (id, power_name) VALUES (39,'Enhanced Senses')
INTO superpower (id, power_name) VALUES (40,'Telekinesis')
INTO superpower (id, power_name) VALUES (41,'Energy Beams')
INTO superpower (id, power_name) VALUES (42,'Magic')
INTO superpower (id, power_name) VALUES (43,'Hyperkinesis')
INTO superpower (id, power_name) VALUES (44,'Jump')
INTO superpower (id, power_name) VALUES (45,'Clairvoyance')
INTO superpower (id, power_name) VALUES (46,'Dimensional Travel')
INTO superpower (id, power_name) VALUES (47,'Power Sense')
INTO superpower (id, power_name) VALUES (48,'Shapeshifting')
INTO superpower (id, power_name) VALUES (49,'Peak Human Condition')
INTO superpower (id, power_name) VALUES (50,'Immortality')
INTO superpower (id, power_name) VALUES (51,'Camouflage')
INTO superpower (id, power_name) VALUES (52,'Element Control')
INTO superpower (id, power_name) VALUES (53,'Phasing')
INTO superpower (id, power_name) VALUES (54,'Astral Projection')
INTO superpower (id, power_name) VALUES (55,'Electrical Transport')
INTO superpower (id, power_name) VALUES (56,'Fire Control')
INTO superpower (id, power_name) VALUES (57,'Projection')
INTO superpower (id, power_name) VALUES (58,'Summoning')
INTO superpower (id, power_name) VALUES (59,'Enhanced Memory')
INTO superpower (id, power_name) VALUES (60,'Reflexes')
INTO superpower (id, power_name) VALUES (61,'Invulnerability')
INTO superpower (id, power_name) VALUES (62,'Energy Constructs')
INTO superpower (id, power_name) VALUES (63,'Force Fields')
INTO superpower (id, power_name) VALUES (64,'Self-Sustenance')
INTO superpower (id, power_name) VALUES (65,'Anti-Gravity')
INTO superpower (id, power_name) VALUES (66,'Empathy')
INTO superpower (id, power_name) VALUES (67,'Power Nullifier')
INTO superpower (id, power_name) VALUES (68,'Radiation Control')
INTO superpower (id, power_name) VALUES (69,'Psionic Powers')
INTO superpower (id, power_name) VALUES (70,'Elasticity')
INTO superpower (id, power_name) VALUES (71,'Substance Secretion')
INTO superpower (id, power_name) VALUES (72,'Elemental Transmogrification')
INTO superpower (id, power_name) VALUES (73,'Technopath/Cyberpath')
INTO superpower (id, power_name) VALUES (74,'Photographic Reflexes')
INTO superpower (id, power_name) VALUES (75,'Seismic Power')
INTO superpower (id, power_name) VALUES (76,'Animation')
INTO superpower (id, power_name) VALUES (77,'Precognition')
INTO superpower (id, power_name) VALUES (78,'Mind Control')
INTO superpower (id, power_name) VALUES (79,'Fire Resistance')
INTO superpower (id, power_name) VALUES (80,'Power Absorption')
INTO superpower (id, power_name) VALUES (81,'Enhanced Hearing')
INTO superpower (id, power_name) VALUES (82,'Nova Force')
INTO superpower (id, power_name) VALUES (83,'Insanity')
INTO superpower (id, power_name) VALUES (84,'Hypnokinesis')
INTO superpower (id, power_name) VALUES (85,'Animal Control')
INTO superpower (id, power_name) VALUES (86,'Natural Armor')
INTO superpower (id, power_name) VALUES (87,'Intangibility')
INTO superpower (id, power_name) VALUES (88,'Enhanced Sight')
INTO superpower (id, power_name) VALUES (89,'Molecular Manipulation')
INTO superpower (id, power_name) VALUES (90,'Heat Generation')
INTO superpower (id, power_name) VALUES (91,'Adaptation')
INTO superpower (id, power_name) VALUES (92,'Gliding')
INTO superpower (id, power_name) VALUES (93,'Power Suit')
INTO superpower (id, power_name) VALUES (94,'Mind Blast')
INTO superpower (id, power_name) VALUES (95,'Probability Manipulation')
INTO superpower (id, power_name) VALUES (96,'Gravity Control')
INTO superpower (id, power_name) VALUES (97,'Regeneration')
INTO superpower (id, power_name) VALUES (98,'Light Control')
INTO superpower (id, power_name) VALUES (99,'Echolocation')
INTO superpower (id, power_name) VALUES (100,'Levitation')
INTO superpower (id, power_name) VALUES (101,'Toxin and Disease Control')
INTO superpower (id, power_name) VALUES (102,'Banish')
INTO superpower (id, power_name) VALUES (103,'Energy Manipulation')
INTO superpower (id, power_name) VALUES (104,'Heat Resistance')
INTO superpower (id, power_name) VALUES (105,'Natural Weapons')
INTO superpower (id, power_name) VALUES (106,'Time Travel')
INTO superpower (id, power_name) VALUES (107,'Enhanced Smell')
INTO superpower (id, power_name) VALUES (108,'Illusions')
INTO superpower (id, power_name) VALUES (109,'Thirstokinesis')
INTO superpower (id, power_name) VALUES (110,'Hair Manipulation')
INTO superpower (id, power_name) VALUES (111,'Illumination')
INTO superpower (id, power_name) VALUES (112,'Omnipotent')
INTO superpower (id, power_name) VALUES (113,'Cloaking')
INTO superpower (id, power_name) VALUES (114,'Changing Armor')
INTO superpower (id, power_name) VALUES (115,'Power Cosmic')
INTO superpower (id, power_name) VALUES (116,'Biokinesis')
INTO superpower (id, power_name) VALUES (117,'Water Control')
INTO superpower (id, power_name) VALUES (118,'Radiation Immunity')
INTO superpower (id, power_name) VALUES (119,'Vision - Telescopic')
INTO superpower (id, power_name) VALUES (120,'Toxin and Disease Resistance')
INTO superpower (id, power_name) VALUES (121,'Spatial Awareness')
INTO superpower (id, power_name) VALUES (122,'Energy Resistance')
INTO superpower (id, power_name) VALUES (123,'Telepathy Resistance')
INTO superpower (id, power_name) VALUES (124,'Molecular Combustion')
INTO superpower (id, power_name) VALUES (125,'Omnilingualism')
INTO superpower (id, power_name) VALUES (126,'Portal Creation')
INTO superpower (id, power_name) VALUES (127,'Magnetism')
INTO superpower (id, power_name) VALUES (128,'Mind Control Resistance')
INTO superpower (id, power_name) VALUES (129,'Plant Control')
INTO superpower (id, power_name) VALUES (130,'Sonar')
INTO superpower (id, power_name) VALUES (131,'Sonic Scream')
INTO superpower (id, power_name) VALUES (132,'Time Manipulation')
INTO superpower (id, power_name) VALUES (133,'Enhanced Touch')
INTO superpower (id, power_name) VALUES (134,'Magic Resistance')
INTO superpower (id, power_name) VALUES (135,'Invisibility')
INTO superpower (id, power_name) VALUES (136,'Sub-Mariner')
INTO superpower (id, power_name) VALUES (137,'Radiation Absorption')
INTO superpower (id, power_name) VALUES (138,'Intuitive aptitude')
INTO superpower (id, power_name) VALUES (139,'Vision - Microscopic')
INTO superpower (id, power_name) VALUES (140,'Melting')
INTO superpower (id, power_name) VALUES (141,'Wind Control')
INTO superpower (id, power_name) VALUES (142,'Super Breath')
INTO superpower (id, power_name) VALUES (143,'Wallcrawling')
INTO superpower (id, power_name) VALUES (144,'Vision - Night')
INTO superpower (id, power_name) VALUES (145,'Vision - Infrared')
INTO superpower (id, power_name) VALUES (146,'Grim Reaping')
INTO superpower (id, power_name) VALUES (147,'Matter Absorption')
INTO superpower (id, power_name) VALUES (148,'The Force')
INTO superpower (id, power_name) VALUES (149,'Resurrection')
INTO superpower (id, power_name) VALUES (150,'Terrakinesis')
INTO superpower (id, power_name) VALUES (151,'Vision - Heat')
INTO superpower (id, power_name) VALUES (152,'Vitakinesis')
INTO superpower (id, power_name) VALUES (153,'Radar Sense')
INTO superpower (id, power_name) VALUES (154,'Qwardian Power Ring')
INTO superpower (id, power_name) VALUES (155,'Weather Control')
INTO superpower (id, power_name) VALUES (156,'Vision - X-Ray')
INTO superpower (id, power_name) VALUES (157,'Vision - Thermal')
INTO superpower (id, power_name) VALUES (158,'Web Creation')
INTO superpower (id, power_name) VALUES (159,'Reality Warping')
INTO superpower (id, power_name) VALUES (160,'Odin Force')
INTO superpower (id, power_name) VALUES (161,'Symbiote Costume')
INTO superpower (id, power_name) VALUES (162,'Speed Force')
INTO superpower (id, power_name) VALUES (163,'Phoenix Force')
INTO superpower (id, power_name) VALUES (164,'Molecular Dissipation')
INTO superpower (id, power_name) VALUES (165,'Vision - Cryo')
INTO superpower (id, power_name) VALUES (166,'Omnipresent')
INTO superpower (id, power_name) VALUES (167,'Omniscient')
SELECT * FROM dual;