CREATE SCHEMA olympics
USE olympics;




DROP TABLE IF EXISTS medal;

CREATE TABLE medal (
  id NUMBER(11) NOT NULL,
  medal_name varchar2(50) DEFAULT NULL,
  PRIMARY KEY (id)
);




INSERT ALL
INTO medal (id, medal_name) VALUES (1,'Gold')
INTO medal (id, medal_name) VALUES (2,'Silver')
INTO medal (id, medal_name) VALUES (3,'Bronze')
INTO medal (id, medal_name) VALUES (4,'NA')
SELECT * FROM dual;



DROP TABLE IF EXISTS noc_region;

CREATE TABLE noc_region (
  id NUMBER(11) NOT NULL,
  noc varchar2(5) DEFAULT NULL,
  region_name varchar2(200) DEFAULT NULL,
  PRIMARY KEY (id)
);


INSERT ALL
INTO noc_region (id, noc, region_name) VALUES (1,'AFG','Afghanistan')
INTO noc_region (id, noc, region_name) VALUES (2,'AHO','Netherlands Antilles')
INTO noc_region (id, noc, region_name) VALUES (3,'ALB','Albania')
INTO noc_region (id, noc, region_name) VALUES (4,'ALG','Algeria')
INTO noc_region (id, noc, region_name) VALUES (5,'AND','Andorra')
INTO noc_region (id, noc, region_name) VALUES (6,'ANG','Angola')
INTO noc_region (id, noc, region_name) VALUES (7,'ANT','Antigua and Barbuda')
INTO noc_region (id, noc, region_name) VALUES (8,'ANZ','Australasia')
INTO noc_region (id, noc, region_name) VALUES (9,'ARG','Argentina')
INTO noc_region (id, noc, region_name) VALUES (10,'ARM','Armenia')
INTO noc_region (id, noc, region_name) VALUES (11,'ARU','Aruba')
INTO noc_region (id, noc, region_name) VALUES (12,'ASA','American Samoa')
INTO noc_region (id, noc, region_name) VALUES (13,'AUS','Australia')
INTO noc_region (id, noc, region_name) VALUES (14,'AUT','Austria')
INTO noc_region (id, noc, region_name) VALUES (15,'AZE','Azerbaijan')
INTO noc_region (id, noc, region_name) VALUES (16,'BAH','Bahamas')
INTO noc_region (id, noc, region_name) VALUES (17,'BAN','Bangladesh')
INTO noc_region (id, noc, region_name) VALUES (18,'BAR','Barbados')
INTO noc_region (id, noc, region_name) VALUES (19,'BDI','Burundi')
INTO noc_region (id, noc, region_name) VALUES (20,'BEL','Belgium')
INTO noc_region (id, noc, region_name) VALUES (21,'BEN','Benin')
INTO noc_region (id, noc, region_name) VALUES (22,'BER','Bermuda')
INTO noc_region (id, noc, region_name) VALUES (23,'BHU','Bhutan')
INTO noc_region (id, noc, region_name) VALUES (24,'BIH','Bosnia and Herzegovina')
INTO noc_region (id, noc, region_name) VALUES (25,'BIZ','Belize')
INTO noc_region (id, noc, region_name) VALUES (26,'BLR','Belarus')
INTO noc_region (id, noc, region_name) VALUES (27,'BOH','Bohemia')
INTO noc_region (id, noc, region_name) VALUES (28,'BOL','Boliva')
INTO noc_region (id, noc, region_name) VALUES (29,'BOT','Botswana')
INTO noc_region (id, noc, region_name) VALUES (30,'BRA','Brazil')
INTO noc_region (id, noc, region_name) VALUES (31,'BRN','Bahrain')
INTO noc_region (id, noc, region_name) VALUES (32,'BRU','Brunei')
INTO noc_region (id, noc, region_name) VALUES (33,'BUL','Bulgaria')
INTO noc_region (id, noc, region_name) VALUES (34,'BUR','Burkina Faso')
INTO noc_region (id, noc, region_name) VALUES (35,'CAF','Central African Republic')
INTO noc_region (id, noc, region_name) VALUES (36,'CAM','Cambodia')
INTO noc_region (id, noc, region_name) VALUES (37,'CAN','Canada')
INTO noc_region (id, noc, region_name) VALUES (38,'CAY','Cayman Islands')
INTO noc_region (id, noc, region_name) VALUES (39,'CGO','Republic of Congo')
INTO noc_region (id, noc, region_name) VALUES (40,'CHA','Chad')
INTO noc_region (id, noc, region_name) VALUES (41,'CHI','Chile')
INTO noc_region (id, noc, region_name) VALUES (42,'CHN','China')
INTO noc_region (id, noc, region_name) VALUES (43,'CIV','Ivory Coast')
INTO noc_region (id, noc, region_name) VALUES (44,'CMR','Cameroon')
INTO noc_region (id, noc, region_name) VALUES (45,'COD','Democratic Republic of the Congo')
INTO noc_region (id, noc, region_name) VALUES (46,'COK','Cook Islands')
INTO noc_region (id, noc, region_name) VALUES (47,'COL','Colombia')
INTO noc_region (id, noc, region_name) VALUES (48,'COM','Comoros')
INTO noc_region (id, noc, region_name) VALUES (49,'CPV','Cape Verde')
INTO noc_region (id, noc, region_name) VALUES (50,'CRC','Costa Rica')
INTO noc_region (id, noc, region_name) VALUES (51,'CRO','Croatia')
INTO noc_region (id, noc, region_name) VALUES (52,'CRT','Crete')
INTO noc_region (id, noc, region_name) VALUES (53,'CUB','Cuba')
INTO noc_region (id, noc, region_name) VALUES (54,'CYP','Cyprus')
INTO noc_region (id, noc, region_name) VALUES (55,'CZE','Czech Republic')
INTO noc_region (id, noc, region_name) VALUES (56,'DEN','Denmark')
INTO noc_region (id, noc, region_name) VALUES (57,'DJI','Djibouti')
INTO noc_region (id, noc, region_name) VALUES (58,'DMA','Dominica')
INTO noc_region (id, noc, region_name) VALUES (59,'DOM','Dominican Republic')
INTO noc_region (id, noc, region_name) VALUES (60,'ECU','Ecuador')
INTO noc_region (id, noc, region_name) VALUES (61,'EGY','Egypt')
INTO noc_region (id, noc, region_name) VALUES (62,'ERI','Eritrea')
INTO noc_region (id, noc, region_name) VALUES (63,'ESA','El Salvador')
INTO noc_region (id, noc, region_name) VALUES (64,'ESP','Spain')
INTO noc_region (id, noc, region_name) VALUES (65,'EST','Estonia')
INTO noc_region (id, noc, region_name) VALUES (66,'ETH','Ethiopia')
INTO noc_region (id, noc, region_name) VALUES (67,'EUN','Unified Team')
INTO noc_region (id, noc, region_name) VALUES (68,'FIJ','Fiji')
INTO noc_region (id, noc, region_name) VALUES (69,'FIN','Finland')
INTO noc_region (id, noc, region_name) VALUES (70,'FRA','France')
INTO noc_region (id, noc, region_name) VALUES (71,'FRG','West Germany')
INTO noc_region (id, noc, region_name) VALUES (72,'FSM','Micronesia')
INTO noc_region (id, noc, region_name) VALUES (73,'GAB','Gabon')
INTO noc_region (id, noc, region_name) VALUES (74,'GAM','Gambia')
INTO noc_region (id, noc, region_name) VALUES (75,'GBR','UK')
INTO noc_region (id, noc, region_name) VALUES (76,'GBS','Guinea-Bissau')
INTO noc_region (id, noc, region_name) VALUES (77,'GDR','East Germany')
INTO noc_region (id, noc, region_name) VALUES (78,'GEO','Georgia')
INTO noc_region (id, noc, region_name) VALUES (79,'GEQ','Equatorial Guinea')
INTO noc_region (id, noc, region_name) VALUES (80,'GER','Germany')
INTO noc_region (id, noc, region_name) VALUES (81,'GHA','Ghana')
INTO noc_region (id, noc, region_name) VALUES (82,'GRE','Greece')
INTO noc_region (id, noc, region_name) VALUES (83,'GRN','Grenada')
INTO noc_region (id, noc, region_name) VALUES (84,'GUA','Guatemala')
INTO noc_region (id, noc, region_name) VALUES (85,'GUI','Guinea')
INTO noc_region (id, noc, region_name) VALUES (86,'GUM','Guam')
INTO noc_region (id, noc, region_name) VALUES (87,'GUY','Guyana')
INTO noc_region (id, noc, region_name) VALUES (88,'HAI','Haiti')
INTO noc_region (id, noc, region_name) VALUES (89,'HKG','Hong Kong')
INTO noc_region (id, noc, region_name) VALUES (90,'HON','Honduras')
INTO noc_region (id, noc, region_name) VALUES (91,'HUN','Hungary')
INTO noc_region (id, noc, region_name) VALUES (92,'INA','Indonesia')
INTO noc_region (id, noc, region_name) VALUES (93,'IND','India')
INTO noc_region (id, noc, region_name) VALUES (94,'IOA','Individual Olympic Athletes')
INTO noc_region (id, noc, region_name) VALUES (95,'IRI','Iran')
INTO noc_region (id, noc, region_name) VALUES (96,'IRL','Ireland')
INTO noc_region (id, noc, region_name) VALUES (97,'IRQ','Iraq')
INTO noc_region (id, noc, region_name) VALUES (98,'ISL','Iceland')
INTO noc_region (id, noc, region_name) VALUES (99,'ISR','Israel')
INTO noc_region (id, noc, region_name) VALUES (100,'ISV','Virgin Islands')
INTO noc_region (id, noc, region_name) VALUES (101,'ITA','Italy')
INTO noc_region (id, noc, region_name) VALUES (102,'IVB','Virgin Islands, British')
INTO noc_region (id, noc, region_name) VALUES (103,'JAM','Jamaica')
INTO noc_region (id, noc, region_name) VALUES (104,'JOR','Jordan')
INTO noc_region (id, noc, region_name) VALUES (105,'JPN','Japan')
INTO noc_region (id, noc, region_name) VALUES (106,'KAZ','Kazakhstan')
INTO noc_region (id, noc, region_name) VALUES (107,'KEN','Kenya')
INTO noc_region (id, noc, region_name) VALUES (108,'KGZ','Kyrgyzstan')
INTO noc_region (id, noc, region_name) VALUES (109,'KIR','Kiribati')
INTO noc_region (id, noc, region_name) VALUES (110,'KOR','South Korea')
INTO noc_region (id, noc, region_name) VALUES (111,'KOS','Kosovo')
INTO noc_region (id, noc, region_name) VALUES (112,'KSA','Saudi Arabia')
INTO noc_region (id, noc, region_name) VALUES (113,'KUW','Kuwait')
INTO noc_region (id, noc, region_name) VALUES (114,'LAO','Laos')
INTO noc_region (id, noc, region_name) VALUES (115,'LAT','Latvia')
INTO noc_region (id, noc, region_name) VALUES (116,'LBA','Libya')
INTO noc_region (id, noc, region_name) VALUES (117,'LBR','Liberia')
INTO noc_region (id, noc, region_name) VALUES (118,'LCA','Saint Lucia')
INTO noc_region (id, noc, region_name) VALUES (119,'LES','Lesotho')
INTO noc_region (id, noc, region_name) VALUES (120,'LIB','Lebanon')
INTO noc_region (id, noc, region_name) VALUES (121,'LIE','Liechtenstein')
INTO noc_region (id, noc, region_name) VALUES (122,'LTU','Lithuania')
INTO noc_region (id, noc, region_name) VALUES (123,'LUX','Luxembourg')
INTO noc_region (id, noc, region_name) VALUES (124,'MAD','Madagascar')
INTO noc_region (id, noc, region_name) VALUES (125,'MAL','Malaya')
INTO noc_region (id, noc, region_name) VALUES (126,'MAR','Morocco')
INTO noc_region (id, noc, region_name) VALUES (127,'MAS','Malaysia')
INTO noc_region (id, noc, region_name) VALUES (128,'MAW','Malawi')
INTO noc_region (id, noc, region_name) VALUES (129,'MDA','Moldova')
INTO noc_region (id, noc, region_name) VALUES (130,'MDV','Maldives')
INTO noc_region (id, noc, region_name) VALUES (131,'MEX','Mexico')
INTO noc_region (id, noc, region_name) VALUES (132,'MGL','Mongolia')
INTO noc_region (id, noc, region_name) VALUES (133,'MHL','Marshall Islands')
INTO noc_region (id, noc, region_name) VALUES (134,'MKD','Macedonia')
INTO noc_region (id, noc, region_name) VALUES (135,'MLI','Mali')
INTO noc_region (id, noc, region_name) VALUES (136,'MLT','Malta')
INTO noc_region (id, noc, region_name) VALUES (137,'MNE','Montenegro')
INTO noc_region (id, noc, region_name) VALUES (138,'MON','Monaco')
INTO noc_region (id, noc, region_name) VALUES (139,'MOZ','Mozambique')
INTO noc_region (id, noc, region_name) VALUES (140,'MRI','Mauritius')
INTO noc_region (id, noc, region_name) VALUES (141,'MTN','Mauritania')
INTO noc_region (id, noc, region_name) VALUES (142,'MYA','Myanmar')
INTO noc_region (id, noc, region_name) VALUES (143,'NAM','Namibia')
INTO noc_region (id, noc, region_name) VALUES (144,'NBO','North Borneo')
INTO noc_region (id, noc, region_name) VALUES (145,'NCA','Nicaragua')
INTO noc_region (id, noc, region_name) VALUES (146,'NED','Netherlands')
INTO noc_region (id, noc, region_name) VALUES (147,'NEP','Nepal')
INTO noc_region (id, noc, region_name) VALUES (148,'NFL','Newfoundland')
INTO noc_region (id, noc, region_name) VALUES (149,'NGR','Nigeria')
INTO noc_region (id, noc, region_name) VALUES (150,'NIG','Niger')
INTO noc_region (id, noc, region_name) VALUES (151,'NOR','Norway')
INTO noc_region (id, noc, region_name) VALUES (152,'NRU','Nauru')
INTO noc_region (id, noc, region_name) VALUES (153,'NZL','New Zealand')
INTO noc_region (id, noc, region_name) VALUES (154,'OMA','Oman')
INTO noc_region (id, noc, region_name) VALUES (155,'PAK','Pakistan')
INTO noc_region (id, noc, region_name) VALUES (156,'PAN','Panama')
INTO noc_region (id, noc, region_name) VALUES (157,'PAR','Paraguay')
INTO noc_region (id, noc, region_name) VALUES (158,'PER','Peru')
INTO noc_region (id, noc, region_name) VALUES (159,'PHI','Philippines')
INTO noc_region (id, noc, region_name) VALUES (160,'PLE','Palestine')
INTO noc_region (id, noc, region_name) VALUES (161,'PLW','Palau')
INTO noc_region (id, noc, region_name) VALUES (162,'PNG','Papua New Guinea')
INTO noc_region (id, noc, region_name) VALUES (163,'POL','Poland')
INTO noc_region (id, noc, region_name) VALUES (164,'POR','Portugal')
INTO noc_region (id, noc, region_name) VALUES (165,'PRK','North Korea')
INTO noc_region (id, noc, region_name) VALUES (166,'PUR','Puerto Rico')
INTO noc_region (id, noc, region_name) VALUES (167,'QAT','Qatar')
INTO noc_region (id, noc, region_name) VALUES (168,'RHO','Zimbabwe (Rhodesia)')
INTO noc_region (id, noc, region_name) VALUES (169,'ROT','Refugee Olympic Team')
INTO noc_region (id, noc, region_name) VALUES (170,'ROU','Romania')
INTO noc_region (id, noc, region_name) VALUES (171,'RSA','South Africa')
INTO noc_region (id, noc, region_name) VALUES (172,'RUS','Russia')
INTO noc_region (id, noc, region_name) VALUES (173,'RWA','Rwanda')
INTO noc_region (id, noc, region_name) VALUES (174,'SAA','Saar')
INTO noc_region (id, noc, region_name) VALUES (175,'SAM','Samoa')
INTO noc_region (id, noc, region_name) VALUES (176,'SCG','Serbia and Montenegro')
INTO noc_region (id, noc, region_name) VALUES (177,'SEN','Senegal')
INTO noc_region (id, noc, region_name) VALUES (178,'SEY','Seychelles')
INTO noc_region (id, noc, region_name) VALUES (179,'SIN','Singapore')
INTO noc_region (id, noc, region_name) VALUES (180,'SKN','Turks and Caicos Islands')
INTO noc_region (id, noc, region_name) VALUES (181,'SLE','Sierra Leone')
INTO noc_region (id, noc, region_name) VALUES (182,'SLO','Slovenia')
INTO noc_region (id, noc, region_name) VALUES (183,'SMR','San Marino')
INTO noc_region (id, noc, region_name) VALUES (184,'SOL','Solomon Islands')
INTO noc_region (id, noc, region_name) VALUES (185,'SOM','Somalia')
INTO noc_region (id, noc, region_name) VALUES (186,'SRB','Serbia')
INTO noc_region (id, noc, region_name) VALUES (187,'SRI','Sri Lanka')
INTO noc_region (id, noc, region_name) VALUES (188,'SSD','South Sudan')
INTO noc_region (id, noc, region_name) VALUES (189,'STP','Sao Tome and Principe')
INTO noc_region (id, noc, region_name) VALUES (190,'SUD','Sudan')
INTO noc_region (id, noc, region_name) VALUES (191,'SUI','Switzerland')
INTO noc_region (id, noc, region_name) VALUES (192,'SUR','Suriname')
INTO noc_region (id, noc, region_name) VALUES (193,'SVK','Slovakia')
INTO noc_region (id, noc, region_name) VALUES (194,'SWE','Sweden')
INTO noc_region (id, noc, region_name) VALUES (195,'SWZ','Swaziland')
INTO noc_region (id, noc, region_name) VALUES (196,'SYR','Syria')
INTO noc_region (id, noc, region_name) VALUES (197,'TAN','Tanzania')
INTO noc_region (id, noc, region_name) VALUES (198,'TCH','Czechoslovakia')
INTO noc_region (id, noc, region_name) VALUES (199,'TGA','Tonga')
INTO noc_region (id, noc, region_name) VALUES (200,'THA','Thailand')
INTO noc_region (id, noc, region_name) VALUES (201,'TJK','Tajikistan')
INTO noc_region (id, noc, region_name) VALUES (202,'TKM','Turkmenistan')
INTO noc_region (id, noc, region_name) VALUES (203,'TLS','Timor-Leste')
INTO noc_region (id, noc, region_name) VALUES (204,'TOG','Togo')
INTO noc_region (id, noc, region_name) VALUES (205,'TPE','Taiwan')
INTO noc_region (id, noc, region_name) VALUES (206,'TTO','Trinidad and Tobago')
INTO noc_region (id, noc, region_name) VALUES (207,'TUN','Tunisia')
INTO noc_region (id, noc, region_name) VALUES (208,'TUR','Turkey')
INTO noc_region (id, noc, region_name) VALUES (209,'TUV','Tuvalu')
INTO noc_region (id, noc, region_name) VALUES (210,'UAE','United Arab Emirates')
INTO noc_region (id, noc, region_name) VALUES (211,'UAR','United Arab Republic')
INTO noc_region (id, noc, region_name) VALUES (212,'UGA','Uganda')
INTO noc_region (id, noc, region_name) VALUES (213,'UKR','Ukraine')
INTO noc_region (id, noc, region_name) VALUES (214,'UNK','Unknown')
INTO noc_region (id, noc, region_name) VALUES (215,'URS','Soviet Union')
INTO noc_region (id, noc, region_name) VALUES (216,'URU','Uruguay')
INTO noc_region (id, noc, region_name) VALUES (217,'USA','USA')
INTO noc_region (id, noc, region_name) VALUES (218,'UZB','Uzbekistan')
INTO noc_region (id, noc, region_name) VALUES (219,'VAN','Vanuatu')
INTO noc_region (id, noc, region_name) VALUES (220,'VEN','Venezuela')
INTO noc_region (id, noc, region_name) VALUES (221,'VIE','Vietnam')
INTO noc_region (id, noc, region_name) VALUES (222,'VIN','Saint Vincent')
INTO noc_region (id, noc, region_name) VALUES (223,'VNM','Vietnam (pre)')
INTO noc_region (id, noc, region_name) VALUES (224,'WIF','West Indies Federation')
INTO noc_region (id, noc, region_name) VALUES (225,'YAR','North Yemen')
INTO noc_region (id, noc, region_name) VALUES (226,'YEM','Yemen')
INTO noc_region (id, noc, region_name) VALUES (227,'YMD','South Yemen')
INTO noc_region (id, noc, region_name) VALUES (228,'YUG','Yugoslavia')
INTO noc_region (id, noc, region_name) VALUES (229,'ZAM','Zambia')
INTO noc_region (id, noc, region_name) VALUES (230,'ZIM','Zimbabwe')
INTO noc_region (id, noc, region_name) VALUES (256,'SGP','Singapore')
SELECT * FROM dual;



DROP TABLE IF EXISTS sport;

CREATE TABLE sport (
  id NUMBER(11) NOT NULL,
  sport_name varchar2(200) DEFAULT NULL,
  PRIMARY KEY (id)
);




INSERT ALL
INTO sport (id, sport_name) VALUES (1,'Aeronautics')
INTO sport (id, sport_name) VALUES (2,'Alpine Skiing')
INTO sport (id, sport_name) VALUES (3,'Alpinism')
INTO sport (id, sport_name) VALUES (4,'Archery')
INTO sport (id, sport_name) VALUES (5,'Art Competitions')
INTO sport (id, sport_name) VALUES (6,'Athletics')
INTO sport (id, sport_name) VALUES (7,'Badminton')
INTO sport (id, sport_name) VALUES (8,'Baseball')
INTO sport (id, sport_name) VALUES (9,'Basketball')
INTO sport (id, sport_name) VALUES (10,'Basque Pelota')
INTO sport (id, sport_name) VALUES (11,'Beach Volleyball')
INTO sport (id, sport_name) VALUES (12,'Biathlon')
INTO sport (id, sport_name) VALUES (13,'Bobsleigh')
INTO sport (id, sport_name) VALUES (14,'Boxing')
INTO sport (id, sport_name) VALUES (15,'Canoeing')
INTO sport (id, sport_name) VALUES (16,'Cricket')
INTO sport (id, sport_name) VALUES (17,'Croquet')
INTO sport (id, sport_name) VALUES (18,'Cross Country Skiing')
INTO sport (id, sport_name) VALUES (19,'Curling')
INTO sport (id, sport_name) VALUES (20,'Cycling')
INTO sport (id, sport_name) VALUES (21,'Diving')
INTO sport (id, sport_name) VALUES (22,'Equestrianism')
INTO sport (id, sport_name) VALUES (23,'Fencing')
INTO sport (id, sport_name) VALUES (24,'Figure Skating')
INTO sport (id, sport_name) VALUES (25,'Football')
INTO sport (id, sport_name) VALUES (26,'Freestyle Skiing')
INTO sport (id, sport_name) VALUES (27,'Golf')
INTO sport (id, sport_name) VALUES (28,'Gymnastics')
INTO sport (id, sport_name) VALUES (29,'Handball')
INTO sport (id, sport_name) VALUES (30,'Hockey')
INTO sport (id, sport_name) VALUES (31,'Ice Hockey')
INTO sport (id, sport_name) VALUES (32,'Jeu De Paume')
INTO sport (id, sport_name) VALUES (33,'Judo')
INTO sport (id, sport_name) VALUES (34,'Lacrosse')
INTO sport (id, sport_name) VALUES (35,'Luge')
INTO sport (id, sport_name) VALUES (36,'Military Ski Patrol')
INTO sport (id, sport_name) VALUES (37,'Modern Pentathlon')
INTO sport (id, sport_name) VALUES (38,'Motorboating')
INTO sport (id, sport_name) VALUES (39,'Nordic Combined')
INTO sport (id, sport_name) VALUES (40,'Polo')
INTO sport (id, sport_name) VALUES (41,'Racquets')
INTO sport (id, sport_name) VALUES (42,'Rhythmic Gymnastics')
INTO sport (id, sport_name) VALUES (43,'Roque')
INTO sport (id, sport_name) VALUES (44,'Rowing')
INTO sport (id, sport_name) VALUES (45,'Rugby')
INTO sport (id, sport_name) VALUES (46,'Rugby Sevens')
INTO sport (id, sport_name) VALUES (47,'Sailing')
INTO sport (id, sport_name) VALUES (48,'Shooting')
INTO sport (id, sport_name) VALUES (49,'Short Track Speed Skating')
INTO sport (id, sport_name) VALUES (50,'Skeleton')
INTO sport (id, sport_name) VALUES (51,'Ski Jumping')
INTO sport (id, sport_name) VALUES (52,'Snowboarding')
INTO sport (id, sport_name) VALUES (53,'Softball')
INTO sport (id, sport_name) VALUES (54,'Speed Skating')
INTO sport (id, sport_name) VALUES (55,'Swimming')
INTO sport (id, sport_name) VALUES (56,'Synchronized Swimming')
INTO sport (id, sport_name) VALUES (57,'Table Tennis')
INTO sport (id, sport_name) VALUES (58,'Taekwondo')
INTO sport (id, sport_name) VALUES (59,'Tennis')
INTO sport (id, sport_name) VALUES (60,'Trampolining')
INTO sport (id, sport_name) VALUES (61,'Triathlon')
INTO sport (id, sport_name) VALUES (62,'Tug-Of-War')
INTO sport (id, sport_name) VALUES (63,'Volleyball')
INTO sport (id, sport_name) VALUES (64,'Water Polo')
INTO sport (id, sport_name) VALUES (65,'Weightlifting')
INTO sport (id, sport_name) VALUES (66,'Wrestling')
SELECT * FROM dual;


DROP TABLE IF EXISTS city;


CREATE TABLE city (
  id NUMBER(11) NOT NULL,
  city_name varchar2(200) DEFAULT NULL,
  PRIMARY KEY (id)
);




INSERT ALL
INTO city (id, city_name) VALUES (1,'Barcelona')
INTO city (id, city_name) VALUES (2,'London')
INTO city (id, city_name) VALUES (3,'Antwerpen')
INTO city (id, city_name) VALUES (4,'Paris')
INTO city (id, city_name) VALUES (5,'Calgary')
INTO city (id, city_name) VALUES (6,'Albertville')
INTO city (id, city_name) VALUES (7,'Lillehammer')
INTO city (id, city_name) VALUES (8,'Los Angeles')
INTO city (id, city_name) VALUES (9,'Salt Lake City')
INTO city (id, city_name) VALUES (10,'Helsinki')
INTO city (id, city_name) VALUES (11,'Lake Placid')
INTO city (id, city_name) VALUES (12,'Sydney')
INTO city (id, city_name) VALUES (13,'Atlanta')
INTO city (id, city_name) VALUES (14,'Stockholm')
INTO city (id, city_name) VALUES (15,'Sochi')
INTO city (id, city_name) VALUES (16,'Nagano')
INTO city (id, city_name) VALUES (17,'Torino')
INTO city (id, city_name) VALUES (18,'Beijing')
INTO city (id, city_name) VALUES (19,'Rio de Janeiro')
INTO city (id, city_name) VALUES (20,'Athina')
INTO city (id, city_name) VALUES (21,'Squaw Valley')
INTO city (id, city_name) VALUES (22,'Innsbruck')
INTO city (id, city_name) VALUES (23,'Sarajevo')
INTO city (id, city_name) VALUES (24,'Mexico City')
INTO city (id, city_name) VALUES (25,'Munich')
INTO city (id, city_name) VALUES (26,'Seoul')
INTO city (id, city_name) VALUES (27,'Berlin')
INTO city (id, city_name) VALUES (28,'Oslo')
INTO city (id, city_name) VALUES (29,'Cortina d''Ampezzo')
INTO city (id, city_name) VALUES (30,'Melbourne')
INTO city (id, city_name) VALUES (31,'Roma')
INTO city (id, city_name) VALUES (32,'Amsterdam')
INTO city (id, city_name) VALUES (33,'Montreal')
INTO city (id, city_name) VALUES (34,'Moskva')
INTO city (id, city_name) VALUES (35,'Tokyo')
INTO city (id, city_name) VALUES (36,'Vancouver')
INTO city (id, city_name) VALUES (37,'Grenoble')
INTO city (id, city_name) VALUES (38,'Sapporo')
INTO city (id, city_name) VALUES (39,'Chamonix')
INTO city (id, city_name) VALUES (40,'St. Louis')
INTO city (id, city_name) VALUES (41,'Sankt Moritz')
INTO city (id, city_name) VALUES (42,'Garmisch-Partenkirchen')
SELECT * FROM dual;


