--Script to create and populate the video games database

--Ensures & characters are not prompted when the script is run
SET DEFINE OFF;

DROP TABLE region_sales;
DROP TABLE region;
DROP TABLE game_platform;
DROP TABLE game_publisher;
DROP TABLE game;
DROP TABLE publisher;
DROP TABLE genre;
DROP TABLE platform;


--Create tables
CREATE TABLE platform (
	id NUMBER PRIMARY KEY,
	platform_name VARCHAR2(50)
);

CREATE TABLE genre (
	id NUMBER PRIMARY KEY,
	genre_name VARCHAR2(50)
);

CREATE TABLE publisher (
	id NUMBER PRIMARY KEY,
	publisher_name VARCHAR2(100)
);

CREATE TABLE region (
	id NUMBER PRIMARY KEY,
	region_name VARCHAR2(50)
);



INSERT ALL
INTO genre (id, genre_name) VALUES (1,'Action')
INTO genre (id, genre_name) VALUES (2,'Adventure')
INTO genre (id, genre_name) VALUES (3,'Fighting')
INTO genre (id, genre_name) VALUES (4,'Misc')
INTO genre (id, genre_name) VALUES (5,'Platform')
INTO genre (id, genre_name) VALUES (6,'Puzzle')
INTO genre (id, genre_name) VALUES (7,'Racing')
INTO genre (id, genre_name) VALUES (8,'Role-Playing')
INTO genre (id, genre_name) VALUES (9,'Shooter')
INTO genre (id, genre_name) VALUES (10,'Simulation')
INTO genre (id, genre_name) VALUES (11,'Sports')
INTO genre (id, genre_name) VALUES (12,'Strategy')
SELECT * FROM dual;

INSERT ALL
INTO platform (id, platform_name) VALUES (1,'Wii')
INTO platform (id, platform_name) VALUES (2,'NES')
INTO platform (id, platform_name) VALUES (3,'GB')
INTO platform (id, platform_name) VALUES (4,'DS')
INTO platform (id, platform_name) VALUES (5,'X360')
INTO platform (id, platform_name) VALUES (6,'PS3')
INTO platform (id, platform_name) VALUES (7,'PS2')
INTO platform (id, platform_name) VALUES (8,'SNES')
INTO platform (id, platform_name) VALUES (9,'GBA')
INTO platform (id, platform_name) VALUES (10,'3DS')
INTO platform (id, platform_name) VALUES (11,'PS4')
INTO platform (id, platform_name) VALUES (12,'N64')
INTO platform (id, platform_name) VALUES (13,'PS')
INTO platform (id, platform_name) VALUES (14,'XB')
INTO platform (id, platform_name) VALUES (15,'PC')
INTO platform (id, platform_name) VALUES (16,'2600')
INTO platform (id, platform_name) VALUES (17,'PSP')
INTO platform (id, platform_name) VALUES (18,'XOne')
INTO platform (id, platform_name) VALUES (19,'GC')
INTO platform (id, platform_name) VALUES (20,'WiiU')
INTO platform (id, platform_name) VALUES (21,'GEN')
INTO platform (id, platform_name) VALUES (22,'DC')
INTO platform (id, platform_name) VALUES (23,'PSV')
INTO platform (id, platform_name) VALUES (24,'SAT')
INTO platform (id, platform_name) VALUES (25,'SCD')
INTO platform (id, platform_name) VALUES (26,'WS')
INTO platform (id, platform_name) VALUES (27,'NG')
INTO platform (id, platform_name) VALUES (28,'TG16')
INTO platform (id, platform_name) VALUES (29,'3DO')
INTO platform (id, platform_name) VALUES (30,'GG')
INTO platform (id, platform_name) VALUES (31,'PCFX')
SELECT * FROM dual;

INSERT ALL
INTO publisher (id, publisher_name) VALUES (1,'10TACLE Studios')
INTO publisher (id, publisher_name) VALUES (2,'1C Company')
INTO publisher (id, publisher_name) VALUES (3,'20th Century Fox Video Games')
INTO publisher (id, publisher_name) VALUES (4,'2D Boy')
INTO publisher (id, publisher_name) VALUES (5,'3DO')
INTO publisher (id, publisher_name) VALUES (6,'49Games')
INTO publisher (id, publisher_name) VALUES (7,'505 Games')
INTO publisher (id, publisher_name) VALUES (8,'5pb')
INTO publisher (id, publisher_name) VALUES (9,'7G//AMES')
INTO publisher (id, publisher_name) VALUES (10,'989 Sports')
INTO publisher (id, publisher_name) VALUES (11,'989 Studios')
INTO publisher (id, publisher_name) VALUES (12,'Abylight')
INTO publisher (id, publisher_name) VALUES (13,'Acclaim Entertainment')
INTO publisher (id, publisher_name) VALUES (14,'Accolade')
INTO publisher (id, publisher_name) VALUES (15,'Ackkstudios')
INTO publisher (id, publisher_name) VALUES (16,'Acquire')
INTO publisher (id, publisher_name) VALUES (17,'Activision')
INTO publisher (id, publisher_name) VALUES (18,'Activision Blizzard')
INTO publisher (id, publisher_name) VALUES (19,'Activision Value')
INTO publisher (id, publisher_name) VALUES (20,'Adeline Software')
INTO publisher (id, publisher_name) VALUES (21,'Aerosoft')
INTO publisher (id, publisher_name) VALUES (22,'Agatsuma Entertainment')
INTO publisher (id, publisher_name) VALUES (23,'Agetec')
INTO publisher (id, publisher_name) VALUES (24,'Aksys Games')
INTO publisher (id, publisher_name) VALUES (25,'Alawar Entertainment')
INTO publisher (id, publisher_name) VALUES (26,'Alchemist')
INTO publisher (id, publisher_name) VALUES (27,'Alternative Software')
INTO publisher (id, publisher_name) VALUES (28,'Altron')
INTO publisher (id, publisher_name) VALUES (29,'Alvion')
INTO publisher (id, publisher_name) VALUES (30,'American Softworks')
INTO publisher (id, publisher_name) VALUES (31,'Angel Studios')
INTO publisher (id, publisher_name) VALUES (32,'Answer Software')
INTO publisher (id, publisher_name) VALUES (33,'AQ Interactive')
INTO publisher (id, publisher_name) VALUES (34,'Aqua Plus')
INTO publisher (id, publisher_name) VALUES (35,'Aques')
INTO publisher (id, publisher_name) VALUES (36,'Arc System Works')
INTO publisher (id, publisher_name) VALUES (37,'Arena Entertainment')
INTO publisher (id, publisher_name) VALUES (38,'Aria')
INTO publisher (id, publisher_name) VALUES (39,'Arika')
INTO publisher (id, publisher_name) VALUES (40,'ArtDink')
INTO publisher (id, publisher_name) VALUES (41,'Aruze Corp')
INTO publisher (id, publisher_name) VALUES (42,'ASC Games')
INTO publisher (id, publisher_name) VALUES (43,'Ascaron Entertainment')
INTO publisher (id, publisher_name) VALUES (44,'Ascaron Entertainment GmbH')
INTO publisher (id, publisher_name) VALUES (45,'ASCII Entertainment')
INTO publisher (id, publisher_name) VALUES (46,'ASCII Media Works')
INTO publisher (id, publisher_name) VALUES (47,'Asgard')
INTO publisher (id, publisher_name) VALUES (48,'ASK')
INTO publisher (id, publisher_name) VALUES (49,'Asmik Ace Entertainment')
INTO publisher (id, publisher_name) VALUES (50,'Asmik Corp')
INTO publisher (id, publisher_name) VALUES (51,'Aspyr')
INTO publisher (id, publisher_name) VALUES (52,'Astragon')
INTO publisher (id, publisher_name) VALUES (53,'Asylum Entertainment')
INTO publisher (id, publisher_name) VALUES (54,'Atari')
INTO publisher (id, publisher_name) VALUES (55,'Athena')
INTO publisher (id, publisher_name) VALUES (56,'Atlus')
INTO publisher (id, publisher_name) VALUES (57,'Avalon Interactive')
INTO publisher (id, publisher_name) VALUES (58,'Avanquest')
INTO publisher (id, publisher_name) VALUES (59,'Avanquest Software')
INTO publisher (id, publisher_name) VALUES (60,'Axela')
INTO publisher (id, publisher_name) VALUES (61,'BAM! Entertainment')
INTO publisher (id, publisher_name) VALUES (62,'Banpresto')
INTO publisher (id, publisher_name) VALUES (63,'Benesse')
INTO publisher (id, publisher_name) VALUES (64,'Berkeley')
INTO publisher (id, publisher_name) VALUES (65,'Bethesda Softworks')
INTO publisher (id, publisher_name) VALUES (66,'Big Ben Interactive')
INTO publisher (id, publisher_name) VALUES (67,'Big Fish Games')
INTO publisher (id, publisher_name) VALUES (68,'Bigben Interactive')
INTO publisher (id, publisher_name) VALUES (69,'bitComposer Games')
INTO publisher (id, publisher_name) VALUES (70,'Black Bean Games')
INTO publisher (id, publisher_name) VALUES (71,'Black Label Games')
INTO publisher (id, publisher_name) VALUES (72,'Blast! Entertainment Ltd')
INTO publisher (id, publisher_name) VALUES (73,'Blue Byte')
INTO publisher (id, publisher_name) VALUES (74,'BMG Interactive Entertainment')
INTO publisher (id, publisher_name) VALUES (75,'Bohemia Interactive')
INTO publisher (id, publisher_name) VALUES (76,'Bomb')
INTO publisher (id, publisher_name) VALUES (77,'Boost On')
INTO publisher (id, publisher_name) VALUES (78,'BPS')
INTO publisher (id, publisher_name) VALUES (79,'Brash Entertainment')
INTO publisher (id, publisher_name) VALUES (80,'Broccoli')
INTO publisher (id, publisher_name) VALUES (81,'BushiRoad')
INTO publisher (id, publisher_name) VALUES (82,'Capcom')
INTO publisher (id, publisher_name) VALUES (83,'Cave')
INTO publisher (id, publisher_name) VALUES (84,'CBS Electronics')
INTO publisher (id, publisher_name) VALUES (85,'CCP')
INTO publisher (id, publisher_name) VALUES (86,'CDV Software Entertainment')
INTO publisher (id, publisher_name) VALUES (87,'ChunSoft')
INTO publisher (id, publisher_name) VALUES (88,'City Interactive')
INTO publisher (id, publisher_name) VALUES (89,'Cloud Imperium Games Corporation')
INTO publisher (id, publisher_name) VALUES (90,'Coconuts Japan')
INTO publisher (id, publisher_name) VALUES (91,'Codemasters')
INTO publisher (id, publisher_name) VALUES (92,'Codemasters Online')
INTO publisher (id, publisher_name) VALUES (93,'CokeM Interactive')
INTO publisher (id, publisher_name) VALUES (94,'Coleco')
INTO publisher (id, publisher_name) VALUES (95,'Comfort')
INTO publisher (id, publisher_name) VALUES (96,'Commseed')
INTO publisher (id, publisher_name) VALUES (97,'Compile')
INTO publisher (id, publisher_name) VALUES (98,'Compile Heart')
INTO publisher (id, publisher_name) VALUES (99,'Conspiracy Entertainment')
INTO publisher (id, publisher_name) VALUES (100,'Core Design Ltd.')
INTO publisher (id, publisher_name) VALUES (101,'CPG Products')
INTO publisher (id, publisher_name) VALUES (102,'Crave Entertainment')
INTO publisher (id, publisher_name) VALUES (103,'Creative Core')
INTO publisher (id, publisher_name) VALUES (104,'Crimson Cow')
INTO publisher (id, publisher_name) VALUES (105,'Crystal Dynamics')
INTO publisher (id, publisher_name) VALUES (106,'CTO SpA')
INTO publisher (id, publisher_name) VALUES (107,'Culture Brain')
INTO publisher (id, publisher_name) VALUES (108,'Culture Publishers')
INTO publisher (id, publisher_name) VALUES (109,'CyberFront')
INTO publisher (id, publisher_name) VALUES (110,'Cygames')
INTO publisher (id, publisher_name) VALUES (111,'D3Publisher')
INTO publisher (id, publisher_name) VALUES (112,'Daedalic')
INTO publisher (id, publisher_name) VALUES (113,'Daedalic Entertainment')
INTO publisher (id, publisher_name) VALUES (114,'Daito')
INTO publisher (id, publisher_name) VALUES (115,'Data Age')
INTO publisher (id, publisher_name) VALUES (116,'Data Design Interactive')
INTO publisher (id, publisher_name) VALUES (117,'Data East')
INTO publisher (id, publisher_name) VALUES (118,'Datam Polystar')
INTO publisher (id, publisher_name) VALUES (119,'Deep Silver')
INTO publisher (id, publisher_name) VALUES (120,'Destination Software, Inc')
INTO publisher (id, publisher_name) VALUES (121,'Destineer')
INTO publisher (id, publisher_name) VALUES (122,'Detn8 Games')
INTO publisher (id, publisher_name) VALUES (123,'Devolver Digital')
INTO publisher (id, publisher_name) VALUES (124,'DHM Interactive')
INTO publisher (id, publisher_name) VALUES (125,'DigiCube')
INTO publisher (id, publisher_name) VALUES (126,'Disney Interactive Studios')
INTO publisher (id, publisher_name) VALUES (127,'Dorart')
INTO publisher (id, publisher_name) VALUES (128,'dramatic create')
INTO publisher (id, publisher_name) VALUES (129,'DreamCatcher Interactive')
INTO publisher (id, publisher_name) VALUES (130,'DreamWorks Interactive')
INTO publisher (id, publisher_name) VALUES (131,'DSI Games')
INTO publisher (id, publisher_name) VALUES (132,'DTP Entertainment')
INTO publisher (id, publisher_name) VALUES (133,'Dusenberry Martin Racing')
INTO publisher (id, publisher_name) VALUES (134,'EA Games')
INTO publisher (id, publisher_name) VALUES (135,'Easy Interactive')
INTO publisher (id, publisher_name) VALUES (136,'Ecole')
INTO publisher (id, publisher_name) VALUES (137,'Edia')
INTO publisher (id, publisher_name) VALUES (138,'Eidos Interactive')
INTO publisher (id, publisher_name) VALUES (139,'Electronic Arts')
INTO publisher (id, publisher_name) VALUES (140,'Electronic Arts Victor')
INTO publisher (id, publisher_name) VALUES (141,'Elf')
INTO publisher (id, publisher_name) VALUES (142,'Elite')
INTO publisher (id, publisher_name) VALUES (143,'Empire Interactive')
INTO publisher (id, publisher_name) VALUES (144,'Encore')
INTO publisher (id, publisher_name) VALUES (145,'Enix Corporation')
INTO publisher (id, publisher_name) VALUES (146,'Enjoy Gaming ltd.')
INTO publisher (id, publisher_name) VALUES (147,'Enterbrain')
INTO publisher (id, publisher_name) VALUES (148,'EON Digital Entertainment')
INTO publisher (id, publisher_name) VALUES (149,'Epic Games')
INTO publisher (id, publisher_name) VALUES (150,'Epoch')
INTO publisher (id, publisher_name) VALUES (151,'Ertain')
INTO publisher (id, publisher_name) VALUES (152,'ESP')
INTO publisher (id, publisher_name) VALUES (153,'Essential Games')
INTO publisher (id, publisher_name) VALUES (154,'Evolution Games')
INTO publisher (id, publisher_name) VALUES (155,'Evolved Games')
INTO publisher (id, publisher_name) VALUES (156,'Excalibur Publishing')
INTO publisher (id, publisher_name) VALUES (157,'Experience Inc.')
INTO publisher (id, publisher_name) VALUES (158,'Extreme Entertainment Group')
INTO publisher (id, publisher_name) VALUES (159,'Falcom Corporation')
INTO publisher (id, publisher_name) VALUES (160,'Fields')
INTO publisher (id, publisher_name) VALUES (161,'Flashpoint Games')
INTO publisher (id, publisher_name) VALUES (162,'Flight-Plan')
INTO publisher (id, publisher_name) VALUES (163,'Focus Home Interactive')
INTO publisher (id, publisher_name) VALUES (164,'Focus Multimedia')
INTO publisher (id, publisher_name) VALUES (165,'fonfun')
INTO publisher (id, publisher_name) VALUES (166,'Foreign Media Games')
INTO publisher (id, publisher_name) VALUES (167,'Fortyfive')
INTO publisher (id, publisher_name) VALUES (168,'Fox Interactive')
INTO publisher (id, publisher_name) VALUES (169,'From Software')
INTO publisher (id, publisher_name) VALUES (170,'Fuji')
INTO publisher (id, publisher_name) VALUES (171,'Funbox Media')
INTO publisher (id, publisher_name) VALUES (172,'Funcom')
INTO publisher (id, publisher_name) VALUES (173,'FunSoft')
INTO publisher (id, publisher_name) VALUES (174,'Funsta')
INTO publisher (id, publisher_name) VALUES (175,'FuRyu')
INTO publisher (id, publisher_name) VALUES (176,'FuRyu Corporation')
INTO publisher (id, publisher_name) VALUES (177,'G.Rev')
INTO publisher (id, publisher_name) VALUES (178,'Gaga')
INTO publisher (id, publisher_name) VALUES (179,'Gainax Network Systems')
INTO publisher (id, publisher_name) VALUES (180,'Gakken')
INTO publisher (id, publisher_name) VALUES (181,'Game Arts')
INTO publisher (id, publisher_name) VALUES (182,'Game Factory')
INTO publisher (id, publisher_name) VALUES (183,'Game Life')
INTO publisher (id, publisher_name) VALUES (184,'Gamebridge')
INTO publisher (id, publisher_name) VALUES (185,'Gamecock')
INTO publisher (id, publisher_name) VALUES (186,'Gameloft')
INTO publisher (id, publisher_name) VALUES (187,'GameMill Entertainment')
INTO publisher (id, publisher_name) VALUES (188,'GameTek')
INTO publisher (id, publisher_name) VALUES (189,'Gathering of Developers')
INTO publisher (id, publisher_name) VALUES (190,'General Entertainment')
INTO publisher (id, publisher_name) VALUES (191,'Genki')
INTO publisher (id, publisher_name) VALUES (192,'Genterprise')
INTO publisher (id, publisher_name) VALUES (193,'Ghostlight')
INTO publisher (id, publisher_name) VALUES (194,'Giga')
INTO publisher (id, publisher_name) VALUES (195,'Giza10')
INTO publisher (id, publisher_name) VALUES (196,'Glams')
INTO publisher (id, publisher_name) VALUES (197,'Global A Entertainment')
INTO publisher (id, publisher_name) VALUES (198,'Global Star')
INTO publisher (id, publisher_name) VALUES (199,'GN Software')
INTO publisher (id, publisher_name) VALUES (200,'GOA')
INTO publisher (id, publisher_name) VALUES (201,'Gotham Games')
INTO publisher (id, publisher_name) VALUES (202,'Graffiti')
INTO publisher (id, publisher_name) VALUES (203,'Grand Prix Games')
INTO publisher (id, publisher_name) VALUES (204,'Graphsim Entertainment')
INTO publisher (id, publisher_name) VALUES (205,'Gremlin Interactive Ltd')
INTO publisher (id, publisher_name) VALUES (206,'Griffin International')
INTO publisher (id, publisher_name) VALUES (207,'Groove Games')
INTO publisher (id, publisher_name) VALUES (208,'GSP')
INTO publisher (id, publisher_name) VALUES (209,'GT Interactive')
INTO publisher (id, publisher_name) VALUES (210,'GungHo')
INTO publisher (id, publisher_name) VALUES (211,'Gust')
INTO publisher (id, publisher_name) VALUES (212,'Hackberry')
INTO publisher (id, publisher_name) VALUES (213,'HAL Laboratory')
INTO publisher (id, publisher_name) VALUES (214,'Hamster Corporation')
INTO publisher (id, publisher_name) VALUES (215,'Happinet')
INTO publisher (id, publisher_name) VALUES (216,'Harmonix Music Systems')
INTO publisher (id, publisher_name) VALUES (217,'Hasbro Interactive')
INTO publisher (id, publisher_name) VALUES (218,'Havas Interactive')
INTO publisher (id, publisher_name) VALUES (219,'Headup Games')
INTO publisher (id, publisher_name) VALUES (220,'Hearty Robin')
INTO publisher (id, publisher_name) VALUES (221,'Hect')
INTO publisher (id, publisher_name) VALUES (222,'Hello Games')
INTO publisher (id, publisher_name) VALUES (223,'Her Interactive')
INTO publisher (id, publisher_name) VALUES (224,'Hip Interactive')
INTO publisher (id, publisher_name) VALUES (225,'HMH Interactive')
INTO publisher (id, publisher_name) VALUES (226,'Home Entertainment Suppliers')
INTO publisher (id, publisher_name) VALUES (227,'Hudson Entertainment')
INTO publisher (id, publisher_name) VALUES (228,'Hudson Soft')
INTO publisher (id, publisher_name) VALUES (229,'Human Entertainment')
INTO publisher (id, publisher_name) VALUES (230,'HuneX')
INTO publisher (id, publisher_name) VALUES (231,'Iceberg Interactive')
INTO publisher (id, publisher_name) VALUES (232,'id Software')
INTO publisher (id, publisher_name) VALUES (233,'Idea Factory')
INTO publisher (id, publisher_name) VALUES (234,'Idea Factory International')
INTO publisher (id, publisher_name) VALUES (235,'IE Institute')
INTO publisher (id, publisher_name) VALUES (236,'Ignition Entertainment')
INTO publisher (id, publisher_name) VALUES (237,'Illusion Softworks')
INTO publisher (id, publisher_name) VALUES (238,'Imadio')
INTO publisher (id, publisher_name) VALUES (239,'Image Epoch')
INTO publisher (id, publisher_name) VALUES (240,'imageepoch Inc.')
INTO publisher (id, publisher_name) VALUES (241,'Imageworks')
INTO publisher (id, publisher_name) VALUES (242,'Imagic')
INTO publisher (id, publisher_name) VALUES (243,'Imagineer')
INTO publisher (id, publisher_name) VALUES (244,'Imax')
INTO publisher (id, publisher_name) VALUES (245,'Indie Games')
INTO publisher (id, publisher_name) VALUES (246,'Infogrames')
INTO publisher (id, publisher_name) VALUES (247,'Insomniac Games')
INTO publisher (id, publisher_name) VALUES (248,'Interchannel')
INTO publisher (id, publisher_name) VALUES (249,'Interchannel-Holon')
INTO publisher (id, publisher_name) VALUES (250,'Intergrow')
INTO publisher (id, publisher_name) VALUES (251,'Interplay')
INTO publisher (id, publisher_name) VALUES (252,'Interplay Productions')
INTO publisher (id, publisher_name) VALUES (253,'Interworks Unlimited, Inc.')
INTO publisher (id, publisher_name) VALUES (254,'Inti Creates')
INTO publisher (id, publisher_name) VALUES (255,'Introversion Software')
INTO publisher (id, publisher_name) VALUES (256,'inXile Entertainment')
INTO publisher (id, publisher_name) VALUES (257,'Irem Software Engineering')
INTO publisher (id, publisher_name) VALUES (258,'ITT Family Games')
INTO publisher (id, publisher_name) VALUES (259,'Ivolgamus')
INTO publisher (id, publisher_name) VALUES (260,'iWin')
INTO publisher (id, publisher_name) VALUES (261,'Jack of All Games')
INTO publisher (id, publisher_name) VALUES (262,'Jaleco')
INTO publisher (id, publisher_name) VALUES (263,'Jester Interactive')
INTO publisher (id, publisher_name) VALUES (264,'Jorudan')
INTO publisher (id, publisher_name) VALUES (265,'JoWood Productions')
INTO publisher (id, publisher_name) VALUES (266,'Just Flight')
INTO publisher (id, publisher_name) VALUES (267,'JVC')
INTO publisher (id, publisher_name) VALUES (268,'Kadokawa Games')
INTO publisher (id, publisher_name) VALUES (269,'Kadokawa Shoten')
INTO publisher (id, publisher_name) VALUES (270,'Kaga Create')
INTO publisher (id, publisher_name) VALUES (271,'Kalypso Media')
INTO publisher (id, publisher_name) VALUES (272,'Kamui')
INTO publisher (id, publisher_name) VALUES (273,'Kando Games')
INTO publisher (id, publisher_name) VALUES (274,'Karin Entertainment')
INTO publisher (id, publisher_name) VALUES (275,'Kemco')
INTO publisher (id, publisher_name) VALUES (276,'KID')
INTO publisher (id, publisher_name) VALUES (277,'Kids Station')
INTO publisher (id, publisher_name) VALUES (278,'King Records')
INTO publisher (id, publisher_name) VALUES (279,'Knowledge Adventure')
INTO publisher (id, publisher_name) VALUES (280,'Koch Media')
INTO publisher (id, publisher_name) VALUES (281,'Kokopeli Digital Studios')
INTO publisher (id, publisher_name) VALUES (282,'Konami Digital Entertainment')
INTO publisher (id, publisher_name) VALUES (283,'Kool Kizz')
INTO publisher (id, publisher_name) VALUES (284,'KSS')
INTO publisher (id, publisher_name) VALUES (285,'Laguna')
INTO publisher (id, publisher_name) VALUES (286,'Legacy Interactive')
INTO publisher (id, publisher_name) VALUES (287,'LEGO Media')
INTO publisher (id, publisher_name) VALUES (288,'Level 5')
INTO publisher (id, publisher_name) VALUES (289,'Lexicon Entertainment')
INTO publisher (id, publisher_name) VALUES (290,'Licensed 4U')
INTO publisher (id, publisher_name) VALUES (291,'Lighthouse Interactive')
INTO publisher (id, publisher_name) VALUES (292,'Liquid Games')
INTO publisher (id, publisher_name) VALUES (293,'Little Orbit')
INTO publisher (id, publisher_name) VALUES (294,'Locus')
INTO publisher (id, publisher_name) VALUES (295,'LSP Games')
INTO publisher (id, publisher_name) VALUES (296,'LucasArts')
INTO publisher (id, publisher_name) VALUES (297,'Mad Catz')
INTO publisher (id, publisher_name) VALUES (298,'Magical Company')
INTO publisher (id, publisher_name) VALUES (299,'Magix')
INTO publisher (id, publisher_name) VALUES (300,'Majesco Entertainment')
INTO publisher (id, publisher_name) VALUES (301,'Mamba Games')
INTO publisher (id, publisher_name) VALUES (302,'Marvel Entertainment')
INTO publisher (id, publisher_name) VALUES (303,'Marvelous Entertainment')
INTO publisher (id, publisher_name) VALUES (304,'Marvelous Games')
INTO publisher (id, publisher_name) VALUES (305,'Marvelous Interactive')
INTO publisher (id, publisher_name) VALUES (306,'Masque Publishing')
INTO publisher (id, publisher_name) VALUES (307,'Mastertronic')
INTO publisher (id, publisher_name) VALUES (308,'Mastiff')
INTO publisher (id, publisher_name) VALUES (309,'Mattel Interactive')
INTO publisher (id, publisher_name) VALUES (310,'Max Five')
INTO publisher (id, publisher_name) VALUES (311,'Maximum Family Games')
INTO publisher (id, publisher_name) VALUES (312,'Maxis')
INTO publisher (id, publisher_name) VALUES (313,'MC2 Entertainment')
INTO publisher (id, publisher_name) VALUES (314,'Media Entertainment')
INTO publisher (id, publisher_name) VALUES (315,'Media Factory')
INTO publisher (id, publisher_name) VALUES (316,'Media Rings')
INTO publisher (id, publisher_name) VALUES (317,'Media Works')
INTO publisher (id, publisher_name) VALUES (318,'MediaQuest')
INTO publisher (id, publisher_name) VALUES (319,'Men-A-Vision')
INTO publisher (id, publisher_name) VALUES (320,'Mentor Interactive')
INTO publisher (id, publisher_name) VALUES (321,'Mercury Games')
INTO publisher (id, publisher_name) VALUES (322,'Merscom LLC')
INTO publisher (id, publisher_name) VALUES (323,'Metro 3D')
INTO publisher (id, publisher_name) VALUES (324,'Michaelsoft')
INTO publisher (id, publisher_name) VALUES (325,'Micro Cabin')
INTO publisher (id, publisher_name) VALUES (326,'Microids')
INTO publisher (id, publisher_name) VALUES (327,'Microprose')
INTO publisher (id, publisher_name) VALUES (328,'Microsoft Game Studios')
INTO publisher (id, publisher_name) VALUES (329,'Midas Interactive Entertainment')
INTO publisher (id, publisher_name) VALUES (330,'Midway Games')
INTO publisher (id, publisher_name) VALUES (331,'Milestone')
INTO publisher (id, publisher_name) VALUES (332,'Milestone S.r.l')
INTO publisher (id, publisher_name) VALUES (333,'Milestone S.r.l.')
INTO publisher (id, publisher_name) VALUES (334,'Minato Station')
INTO publisher (id, publisher_name) VALUES (335,'Mindscape')
INTO publisher (id, publisher_name) VALUES (336,'Mirai Shounen')
INTO publisher (id, publisher_name) VALUES (337,'Misawa')
INTO publisher (id, publisher_name) VALUES (338,'Mitsui')
INTO publisher (id, publisher_name) VALUES (339,'mixi, Inc')
INTO publisher (id, publisher_name) VALUES (340,'MLB.com')
INTO publisher (id, publisher_name) VALUES (341,'Mojang')
INTO publisher (id, publisher_name) VALUES (342,'Monte Christo Multimedia')
INTO publisher (id, publisher_name) VALUES (343,'Moss')
INTO publisher (id, publisher_name) VALUES (344,'MTO')
INTO publisher (id, publisher_name) VALUES (345,'MTV Games')
INTO publisher (id, publisher_name) VALUES (346,'Mud Duck Productions')
INTO publisher (id, publisher_name) VALUES (347,'Mumbo Jumbo')
INTO publisher (id, publisher_name) VALUES (348,'Mycom')
INTO publisher (id, publisher_name) VALUES (349,'Myelin Media')
INTO publisher (id, publisher_name) VALUES (350,'Mystique')
INTO publisher (id, publisher_name) VALUES (351,'N/A')
INTO publisher (id, publisher_name) VALUES (352,'Namco Bandai Games')
INTO publisher (id, publisher_name) VALUES (353,'Natsume')
INTO publisher (id, publisher_name) VALUES (354,'Navarre Corp')
INTO publisher (id, publisher_name) VALUES (355,'Naxat Soft')
INTO publisher (id, publisher_name) VALUES (356,'NCS')
INTO publisher (id, publisher_name) VALUES (357,'NCSoft')
INTO publisher (id, publisher_name) VALUES (358,'NDA Productions')
INTO publisher (id, publisher_name) VALUES (359,'NEC')
INTO publisher (id, publisher_name) VALUES (360,'NEC Interchannel')
INTO publisher (id, publisher_name) VALUES (361,'Neko Entertainment')
INTO publisher (id, publisher_name) VALUES (362,'NetRevo')
INTO publisher (id, publisher_name) VALUES (363,'New')
INTO publisher (id, publisher_name) VALUES (364,'New World Computing')
INTO publisher (id, publisher_name) VALUES (365,'NewKidCo')
INTO publisher (id, publisher_name) VALUES (366,'Nexon')
INTO publisher (id, publisher_name) VALUES (367,'Nichibutsu')
INTO publisher (id, publisher_name) VALUES (368,'Nihon Falcom Corporation')
INTO publisher (id, publisher_name) VALUES (369,'Nintendo')
INTO publisher (id, publisher_name) VALUES (370,'Nippon Amuse')
INTO publisher (id, publisher_name) VALUES (371,'Nippon Columbia')
INTO publisher (id, publisher_name) VALUES (372,'Nippon Ichi Software')
INTO publisher (id, publisher_name) VALUES (373,'Nippon Telenet')
INTO publisher (id, publisher_name) VALUES (374,'Nitroplus')
INTO publisher (id, publisher_name) VALUES (375,'Nobilis')
INTO publisher (id, publisher_name) VALUES (376,'Nordcurrent')
INTO publisher (id, publisher_name) VALUES (377,'Nordic Games')
INTO publisher (id, publisher_name) VALUES (378,'NovaLogic')
INTO publisher (id, publisher_name) VALUES (379,'Number None')
INTO publisher (id, publisher_name) VALUES (380,'O-Games')
INTO publisher (id, publisher_name) VALUES (381,'O3 Entertainment')
INTO publisher (id, publisher_name) VALUES (382,'Ocean')
INTO publisher (id, publisher_name) VALUES (383,'Office Create')
INTO publisher (id, publisher_name) VALUES (384,'On Demand')
INTO publisher (id, publisher_name) VALUES (385,'Ongakukan')
INTO publisher (id, publisher_name) VALUES (386,'Origin Systems')
INTO publisher (id, publisher_name) VALUES (387,'Otomate')
INTO publisher (id, publisher_name) VALUES (388,'Oxygen Interactive')
INTO publisher (id, publisher_name) VALUES (389,'P2 Games')
INTO publisher (id, publisher_name) VALUES (390,'Pacific Century Cyber Works')
INTO publisher (id, publisher_name) VALUES (391,'Pack In Soft')
INTO publisher (id, publisher_name) VALUES (392,'Pack-In-Video')
INTO publisher (id, publisher_name) VALUES (393,'Palcom')
INTO publisher (id, publisher_name) VALUES (394,'Panther Software')
INTO publisher (id, publisher_name) VALUES (395,'Paon')
INTO publisher (id, publisher_name) VALUES (396,'Paon Corporation')
INTO publisher (id, publisher_name) VALUES (397,'Paradox Development')
INTO publisher (id, publisher_name) VALUES (398,'Paradox Interactive')
INTO publisher (id, publisher_name) VALUES (399,'Parker Bros.')
INTO publisher (id, publisher_name) VALUES (400,'Performance Designed Products')
INTO publisher (id, publisher_name) VALUES (401,'Phantagram')
INTO publisher (id, publisher_name) VALUES (402,'Phantom EFX')
INTO publisher (id, publisher_name) VALUES (403,'Phenomedia')
INTO publisher (id, publisher_name) VALUES (404,'Phoenix Games')
INTO publisher (id, publisher_name) VALUES (405,'Piacci')
INTO publisher (id, publisher_name) VALUES (406,'Pinnacle')
INTO publisher (id, publisher_name) VALUES (407,'Pioneer LDC')
INTO publisher (id, publisher_name) VALUES (408,'Play It')
INTO publisher (id, publisher_name) VALUES (409,'Playlogic Game Factory')
INTO publisher (id, publisher_name) VALUES (410,'Playmates')
INTO publisher (id, publisher_name) VALUES (411,'Playmore')
INTO publisher (id, publisher_name) VALUES (412,'PlayV')
INTO publisher (id, publisher_name) VALUES (413,'Plenty')
INTO publisher (id, publisher_name) VALUES (414,'PM Studios')
INTO publisher (id, publisher_name) VALUES (415,'Pony Canyon')
INTO publisher (id, publisher_name) VALUES (416,'PopCap Games')
INTO publisher (id, publisher_name) VALUES (417,'Popcorn Arcade')
INTO publisher (id, publisher_name) VALUES (418,'PopTop Software')
INTO publisher (id, publisher_name) VALUES (419,'Pow')
INTO publisher (id, publisher_name) VALUES (420,'PQube')
INTO publisher (id, publisher_name) VALUES (421,'Princess Soft')
INTO publisher (id, publisher_name) VALUES (422,'Prototype')
INTO publisher (id, publisher_name) VALUES (423,'Psygnosis')
INTO publisher (id, publisher_name) VALUES (424,'Quelle')
INTO publisher (id, publisher_name) VALUES (425,'Quest')
INTO publisher (id, publisher_name) VALUES (426,'Quinrose')
INTO publisher (id, publisher_name) VALUES (427,'Quintet')
INTO publisher (id, publisher_name) VALUES (428,'Rage Software')
INTO publisher (id, publisher_name) VALUES (429,'Rain Games')
INTO publisher (id, publisher_name) VALUES (430,'Rebellion')
INTO publisher (id, publisher_name) VALUES (431,'Rebellion Developments')
INTO publisher (id, publisher_name) VALUES (432,'RED Entertainment')
INTO publisher (id, publisher_name) VALUES (433,'Red Orb')
INTO publisher (id, publisher_name) VALUES (434,'Red Storm Entertainment')
INTO publisher (id, publisher_name) VALUES (435,'RedOctane')
INTO publisher (id, publisher_name) VALUES (436,'Reef Entertainment')
INTO publisher (id, publisher_name) VALUES (437,'responDESIGN')
INTO publisher (id, publisher_name) VALUES (438,'Revolution (Japan)')
INTO publisher (id, publisher_name) VALUES (439,'Revolution Software')
INTO publisher (id, publisher_name) VALUES (440,'Rising Star Games')
INTO publisher (id, publisher_name) VALUES (441,'Riverhillsoft')
INTO publisher (id, publisher_name) VALUES (442,'Rocket Company')
INTO publisher (id, publisher_name) VALUES (443,'Rondomedia')
INTO publisher (id, publisher_name) VALUES (444,'RTL')
INTO publisher (id, publisher_name) VALUES (445,'Russel')
INTO publisher (id, publisher_name) VALUES (446,'Sammy Corporation')
INTO publisher (id, publisher_name) VALUES (447,'Saurus')
INTO publisher (id, publisher_name) VALUES (448,'Scholastic Inc.')
INTO publisher (id, publisher_name) VALUES (449,'SCi')
INTO publisher (id, publisher_name) VALUES (450,'Screenlife')
INTO publisher (id, publisher_name) VALUES (451,'SCS Software')
INTO publisher (id, publisher_name) VALUES (452,'Sega')
INTO publisher (id, publisher_name) VALUES (453,'Seta Corporation')
INTO publisher (id, publisher_name) VALUES (454,'Seventh Chord')
INTO publisher (id, publisher_name) VALUES (455,'Shogakukan')
INTO publisher (id, publisher_name) VALUES (456,'Simon & Schuster Interactive')
INTO publisher (id, publisher_name) VALUES (457,'Slightly Mad Studios')
INTO publisher (id, publisher_name) VALUES (458,'Slitherine Software')
INTO publisher (id, publisher_name) VALUES (459,'SNK')
INTO publisher (id, publisher_name) VALUES (460,'SNK Playmore')
INTO publisher (id, publisher_name) VALUES (461,'Societa')
INTO publisher (id, publisher_name) VALUES (462,'Sold Out')
INTO publisher (id, publisher_name) VALUES (463,'Sonnet')
INTO publisher (id, publisher_name) VALUES (464,'Sony Computer Entertainment')
INTO publisher (id, publisher_name) VALUES (465,'Sony Computer Entertainment America')
INTO publisher (id, publisher_name) VALUES (466,'Sony Computer Entertainment Europe')
INTO publisher (id, publisher_name) VALUES (467,'Sony Music Entertainment')
INTO publisher (id, publisher_name) VALUES (468,'Sony Online Entertainment')
INTO publisher (id, publisher_name) VALUES (469,'SouthPeak Games')
INTO publisher (id, publisher_name) VALUES (470,'Spike')
INTO publisher (id, publisher_name) VALUES (471,'SPS')
INTO publisher (id, publisher_name) VALUES (472,'Square')
INTO publisher (id, publisher_name) VALUES (473,'Square EA')
INTO publisher (id, publisher_name) VALUES (474,'Square Enix')
INTO publisher (id, publisher_name) VALUES (475,'SquareSoft')
INTO publisher (id, publisher_name) VALUES (476,'SSI')
INTO publisher (id, publisher_name) VALUES (477,'Stainless Games')
INTO publisher (id, publisher_name) VALUES (478,'Starfish')
INTO publisher (id, publisher_name) VALUES (479,'Starpath Corp.')
INTO publisher (id, publisher_name) VALUES (480,'Sting')
INTO publisher (id, publisher_name) VALUES (481,'Storm City Games')
INTO publisher (id, publisher_name) VALUES (482,'Strategy First')
INTO publisher (id, publisher_name) VALUES (483,'Success')
INTO publisher (id, publisher_name) VALUES (484,'Summitsoft')
INTO publisher (id, publisher_name) VALUES (485,'Sunflowers')
INTO publisher (id, publisher_name) VALUES (486,'Sunrise Interactive')
INTO publisher (id, publisher_name) VALUES (487,'Sunsoft')
INTO publisher (id, publisher_name) VALUES (488,'Sweets')
INTO publisher (id, publisher_name) VALUES (489,'Swing! Entertainment')
INTO publisher (id, publisher_name) VALUES (490,'Syscom')
INTO publisher (id, publisher_name) VALUES (491,'System 3')
INTO publisher (id, publisher_name) VALUES (492,'System 3 Arcade Software')
INTO publisher (id, publisher_name) VALUES (493,'System Soft')
INTO publisher (id, publisher_name) VALUES (494,'T&E Soft')
INTO publisher (id, publisher_name) VALUES (495,'Taito')
INTO publisher (id, publisher_name) VALUES (496,'Takara')
INTO publisher (id, publisher_name) VALUES (497,'Takara Tomy')
INTO publisher (id, publisher_name) VALUES (498,'Take-Two Interactive')
INTO publisher (id, publisher_name) VALUES (499,'Takuyo')
INTO publisher (id, publisher_name) VALUES (500,'TalonSoft')
INTO publisher (id, publisher_name) VALUES (501,'TDK Core')
INTO publisher (id, publisher_name) VALUES (502,'TDK Mediactive')
INTO publisher (id, publisher_name) VALUES (503,'Team17 Software')
INTO publisher (id, publisher_name) VALUES (504,'Technos Japan Corporation')
INTO publisher (id, publisher_name) VALUES (505,'TechnoSoft')
INTO publisher (id, publisher_name) VALUES (506,'Tecmo Koei')
INTO publisher (id, publisher_name) VALUES (507,'Telegames')
INTO publisher (id, publisher_name) VALUES (508,'Telltale Games')
INTO publisher (id, publisher_name) VALUES (509,'Telstar')
INTO publisher (id, publisher_name) VALUES (510,'Tetris Online')
INTO publisher (id, publisher_name) VALUES (511,'TGL')
INTO publisher (id, publisher_name) VALUES (512,'The Adventure Company')
INTO publisher (id, publisher_name) VALUES (513,'The Learning Company')
INTO publisher (id, publisher_name) VALUES (514,'THQ')
INTO publisher (id, publisher_name) VALUES (515,'Tigervision')
INTO publisher (id, publisher_name) VALUES (516,'Time Warner Interactive')
INTO publisher (id, publisher_name) VALUES (517,'Titus')
INTO publisher (id, publisher_name) VALUES (518,'Tivola')
INTO publisher (id, publisher_name) VALUES (519,'TOHO')
INTO publisher (id, publisher_name) VALUES (520,'Tommo')
INTO publisher (id, publisher_name) VALUES (521,'Tomy Corporation')
INTO publisher (id, publisher_name) VALUES (522,'TopWare Interactive')
INTO publisher (id, publisher_name) VALUES (523,'Touchstone')
INTO publisher (id, publisher_name) VALUES (524,'Tradewest')
INTO publisher (id, publisher_name) VALUES (525,'Trion Worlds')
INTO publisher (id, publisher_name) VALUES (526,'Tripwire Interactive')
INTO publisher (id, publisher_name) VALUES (527,'Tru Blu Entertainment')
INTO publisher (id, publisher_name) VALUES (528,'Tryfirst')
INTO publisher (id, publisher_name) VALUES (529,'TYO')
INTO publisher (id, publisher_name) VALUES (530,'Type-Moon')
INTO publisher (id, publisher_name) VALUES (531,'U.S. Gold')
INTO publisher (id, publisher_name) VALUES (532,'Ubisoft')
INTO publisher (id, publisher_name) VALUES (533,'Ubisoft Annecy')
INTO publisher (id, publisher_name) VALUES (534,'UEP Systems')
INTO publisher (id, publisher_name) VALUES (535,'UFO Interactive')
INTO publisher (id, publisher_name) VALUES (536,'UIG Entertainment')
INTO publisher (id, publisher_name) VALUES (537,'Universal Gamex')
INTO publisher (id, publisher_name) VALUES (538,'Universal Interactive')
INTO publisher (id, publisher_name) VALUES (539,'Unknown')
INTO publisher (id, publisher_name) VALUES (540,'Valcon Games')
INTO publisher (id, publisher_name) VALUES (541,'ValuSoft')
INTO publisher (id, publisher_name) VALUES (542,'Valve')
INTO publisher (id, publisher_name) VALUES (543,'Valve Software')
INTO publisher (id, publisher_name) VALUES (544,'Vap')
INTO publisher (id, publisher_name) VALUES (545,'Vatical Entertainment')
INTO publisher (id, publisher_name) VALUES (546,'Vic Tokai')
INTO publisher (id, publisher_name) VALUES (547,'Victor Interactive')
INTO publisher (id, publisher_name) VALUES (548,'Video System')
INTO publisher (id, publisher_name) VALUES (549,'Views')
INTO publisher (id, publisher_name) VALUES (550,'Vir2L Studios')
INTO publisher (id, publisher_name) VALUES (551,'Virgin Interactive')
INTO publisher (id, publisher_name) VALUES (552,'Virtual Play Games')
INTO publisher (id, publisher_name) VALUES (553,'Visco')
INTO publisher (id, publisher_name) VALUES (554,'Vivendi Games')
INTO publisher (id, publisher_name) VALUES (555,'Wanadoo')
INTO publisher (id, publisher_name) VALUES (556,'Warashi')
INTO publisher (id, publisher_name) VALUES (557,'Wargaming.net')
INTO publisher (id, publisher_name) VALUES (558,'Warner Bros. Interactive Entertainment')
INTO publisher (id, publisher_name) VALUES (559,'Warp')
INTO publisher (id, publisher_name) VALUES (560,'WayForward Technologies')
INTO publisher (id, publisher_name) VALUES (561,'Westwood Studios')
INTO publisher (id, publisher_name) VALUES (562,'White Park Bay Software')
INTO publisher (id, publisher_name) VALUES (563,'Wizard Video Games')
INTO publisher (id, publisher_name) VALUES (564,'Xicat Interactive')
INTO publisher (id, publisher_name) VALUES (565,'Xing Entertainment')
INTO publisher (id, publisher_name) VALUES (566,'Xplosiv')
INTO publisher (id, publisher_name) VALUES (567,'XS Games')
INTO publisher (id, publisher_name) VALUES (568,'Xseed Games')
INTO publisher (id, publisher_name) VALUES (569,'Yacht Club Games')
INTO publisher (id, publisher_name) VALUES (570,'Yamasa Entertainment')
INTO publisher (id, publisher_name) VALUES (571,'Yeti')
INTO publisher (id, publisher_name) VALUES (572,'Yukes')
INTO publisher (id, publisher_name) VALUES (573,'Yumedia')
INTO publisher (id, publisher_name) VALUES (574,'Zenrin')
INTO publisher (id, publisher_name) VALUES (575,'Zoo Digital Publishing')
INTO publisher (id, publisher_name) VALUES (576,'Zoo Games')
INTO publisher (id, publisher_name) VALUES (577,'Zushi Games')
SELECT * FROM dual;

INSERT ALL
INTO region (id, region_name) VALUES (1,'North America')
INTO region (id, region_name) VALUES (2,'Europe')
INTO region (id, region_name) VALUES (3,'Japan')
INTO region (id, region_name) VALUES (4,'Other')
SELECT * FROM dual;
