/*
Scripts used on the Oracle Auto Increment post.
Post here: https://www.databasestar.com/auto_increment-oracle-sql/
*/


CREATE SEQUENCE student_id_seq;


CREATE TRIGGER student_bi
BEFORE INSERT ON student
FOR EACH ROW
BEGIN
  SELECT student_id_seq.nextval
  INTO :new.student_id
  FROM dual;
END;


SELECT student_id, first_name, last_name
FROM student
ORDER BY student_id;

INSERT INTO student (first_name, last_name)
VALUES ('Jason', 'Smith');

SELECT student_id, first_name, last_name
FROM student
ORDER BY student_id;



INSERT INTO student (first_name, last_name)
VALUES ('Joan', 'Colbert');

SELECT student_id, first_name, last_name
FROM student
ORDER BY student_id;

/*
Oracle 12c and above
*/

CREATE TABLE student12c (
student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
first_name VARCHAR2(50),
last_name VARCHAR2(50)
);

INSERT INTO student12c (first_name, last_name)
VALUES ('Jason', 'Smith');

SELECT student_id, first_name, last_name
FROM student12c
ORDER BY student_id;

INSERT INTO student12c (first_name, last_name)
VALUES ('Joan', 'Colbert');

SELECT student_id, first_name, last_name
FROM student12c
ORDER BY student_id;